import type { ActionState, DashboardData, ScoreBreakdown, SignalExplanation } from '@/types/scanner';

function explanation(action: ActionState, triggeredBecause: string[], missingConfirmation: string[], riskNotes: string[]): SignalExplanation {
  return {
    action,
    triggeredBecause,
    missingConfirmation,
    riskNotes,
  };
}

function breakdown(rsiScore: number, macdScore: number, priceLocationScore: number, trendScore: number, volumeScore: number): ScoreBreakdown {
  return {
    rsiScore,
    macdScore,
    priceLocationScore,
    trendScore,
    volumeScore,
  };
}

export const demoDashboardData: DashboardData = {
  generatedFrom: 'demo',
  latestRun: {
    jobName: 'hourly_stock_scanner',
    timeframe: '1h',
    status: 'success',
    startedAt: '2026-06-02T20:00:02Z',
    finishedAt: '2026-06-02T20:00:29Z',
    tickersScanned: 15,
    candlesSaved: 2700,
    indicatorsSaved: 15,
    signalsCreated: 15,
    portfolioOverlaysCreated: 3,
    watchlistOverlaysCreated: 3,
    alertsSent: 2,
  },
  thresholds: {
    alert: 75,
    watchlist: 60,
    signalChange: 8,
  },
  tickers: [
    { symbol: 'AAPL', category: 'mega_cap_platform', companyName: 'Apple', sector: 'Technology', industry: 'Consumer Electronics', exchange: 'NASDAQ', isActive: true },
    { symbol: 'MSFT', category: 'mega_cap_platform', companyName: 'Microsoft', sector: 'Technology', industry: 'Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'NVDA', category: 'ai_infrastructure', companyName: 'Nvidia', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'AMD', category: 'semiconductor', companyName: 'Advanced Micro Devices', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'AVGO', category: 'ai_infrastructure', companyName: 'Broadcom', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'CRM', category: 'enterprise_software', companyName: 'Salesforce', sector: 'Technology', industry: 'Software', exchange: 'NYSE', isActive: true },
    { symbol: 'ADBE', category: 'software', companyName: 'Adobe', sector: 'Technology', industry: 'Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'PANW', category: 'cybersecurity', companyName: 'Palo Alto Networks', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'SNOW', category: 'cloud_data', companyName: 'Snowflake', sector: 'Technology', industry: 'Data Cloud', exchange: 'NYSE', isActive: true },
    { symbol: 'CRWD', category: 'cybersecurity', companyName: 'CrowdStrike', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'NOW', category: 'enterprise_software', companyName: 'ServiceNow', sector: 'Technology', industry: 'Workflow Software', exchange: 'NYSE', isActive: true },
    { symbol: 'DDOG', category: 'cloud_data', companyName: 'Datadog', sector: 'Technology', industry: 'Observability', exchange: 'NASDAQ', isActive: true },
    { symbol: 'AMZN', category: 'mega_cap_platform', companyName: 'Amazon', sector: 'Technology', industry: 'Consumer Internet', exchange: 'NASDAQ', isActive: true },
    { symbol: 'TSM', category: 'ai_infrastructure', companyName: 'Taiwan Semiconductor', sector: 'Technology', industry: 'Semiconductors', exchange: 'NYSE', isActive: true },
    { symbol: 'PLTR', category: 'ai_infrastructure', companyName: 'Palantir Technologies', sector: 'Technology', industry: 'AI Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'SMCI', category: 'ai_infrastructure', companyName: 'Super Micro Computer', sector: 'Technology', industry: 'Hardware', exchange: 'NASDAQ', isActive: true },
    { symbol: 'DELL', category: 'ai_infrastructure', companyName: 'Dell Technologies', sector: 'Technology', industry: 'Hardware', exchange: 'NYSE', isActive: true },
    { symbol: 'ANET', category: 'ai_infrastructure', companyName: 'Arista Networks', sector: 'Technology', industry: 'Networking', exchange: 'NYSE', isActive: true },
    { symbol: 'CRWV', category: 'ai_infrastructure', companyName: 'CoreWeave', sector: 'Technology', industry: 'Cloud GPU', exchange: 'NASDAQ', isActive: true },
    { symbol: 'NBIS', category: 'ai_infrastructure', companyName: 'Nebius Group', sector: 'Technology', industry: 'Cloud GPU', exchange: 'NASDAQ', isActive: true },
    { symbol: 'VRT', category: 'ai_infrastructure', companyName: 'Vertiv Holdings', sector: 'Technology', industry: 'Data Center Infrastructure', exchange: 'NYSE', isActive: true },
    { symbol: 'QRVO', category: 'semiconductor', companyName: 'Qorvo', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'SWKS', category: 'semiconductor', companyName: 'Skyworks Solutions', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'GFS', category: 'semiconductor', companyName: 'GlobalFoundries', sector: 'Technology', industry: 'Semiconductors', exchange: 'NASDAQ', isActive: true },
    { symbol: 'WOLF', category: 'semiconductor', companyName: 'Wolfspeed', sector: 'Technology', industry: 'Semiconductors', exchange: 'NYSE', isActive: true },
    { symbol: 'ENTG', category: 'semiconductor', companyName: 'Entegris', sector: 'Technology', industry: 'Semiconductor Equipment', exchange: 'NASDAQ', isActive: true },
    { symbol: 'TER', category: 'semiconductor', companyName: 'Teradyne', sector: 'Technology', industry: 'Semiconductor Equipment', exchange: 'NASDAQ', isActive: true },
    { symbol: 'COHR', category: 'semiconductor', companyName: 'Coherent', sector: 'Technology', industry: 'Photonics', exchange: 'NYSE', isActive: true },
    { symbol: 'IBM', category: 'software', companyName: 'IBM', sector: 'Technology', industry: 'IT Services', exchange: 'NYSE', isActive: true },
    { symbol: 'ADSK', category: 'software', companyName: 'Autodesk', sector: 'Technology', industry: 'Design Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'ANSS', category: 'software', companyName: 'Ansys', sector: 'Technology', industry: 'Simulation Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'PTC', category: 'software', companyName: 'PTC', sector: 'Technology', industry: 'Industrial Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'HUBS', category: 'software', companyName: 'HubSpot', sector: 'Technology', industry: 'Software', exchange: 'NYSE', isActive: true },
    { symbol: 'DOCU', category: 'software', companyName: 'DocuSign', sector: 'Technology', industry: 'Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'GTLB', category: 'software', companyName: 'GitLab', sector: 'Technology', industry: 'DevOps Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'PATH', category: 'software', companyName: 'UiPath', sector: 'Technology', industry: 'Automation Software', exchange: 'NYSE', isActive: true },
    { symbol: 'AI', category: 'software', companyName: 'C3.ai', sector: 'Technology', industry: 'AI Software', exchange: 'NYSE', isActive: true },
    { symbol: 'TWLO', category: 'software', companyName: 'Twilio', sector: 'Technology', industry: 'Communications Software', exchange: 'NYSE', isActive: true },
    { symbol: 'ZM', category: 'software', companyName: 'Zoom Communications', sector: 'Technology', industry: 'Communications Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'DBX', category: 'software', companyName: 'Dropbox', sector: 'Technology', industry: 'Cloud Software', exchange: 'NASDAQ', isActive: true },
    { symbol: 'NET', category: 'cloud_data', companyName: 'Cloudflare', sector: 'Technology', industry: 'Cloud Infrastructure', exchange: 'NYSE', isActive: true },
    { symbol: 'ESTC', category: 'cloud_data', companyName: 'Elastic', sector: 'Technology', industry: 'Search & Data', exchange: 'NYSE', isActive: true },
    { symbol: 'PSTG', category: 'cloud_data', companyName: 'Pure Storage', sector: 'Technology', industry: 'Data Storage', exchange: 'NYSE', isActive: true },
    { symbol: 'NTAP', category: 'cloud_data', companyName: 'NetApp', sector: 'Technology', industry: 'Data Storage', exchange: 'NASDAQ', isActive: true },
    { symbol: 'DOCN', category: 'cloud_data', companyName: 'DigitalOcean', sector: 'Technology', industry: 'Cloud Infrastructure', exchange: 'NYSE', isActive: true },
    { symbol: 'CFLT', category: 'cloud_data', companyName: 'Confluent', sector: 'Technology', industry: 'Data Streaming', exchange: 'NASDAQ', isActive: true },
    { symbol: 'S', category: 'cybersecurity', companyName: 'SentinelOne', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NYSE', isActive: true },
    { symbol: 'OKTA', category: 'cybersecurity', companyName: 'Okta', sector: 'Technology', industry: 'Identity Security', exchange: 'NASDAQ', isActive: true },
    { symbol: 'CYBR', category: 'cybersecurity', companyName: 'CyberArk Software', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'QLYS', category: 'cybersecurity', companyName: 'Qualys', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'TENB', category: 'cybersecurity', companyName: 'Tenable Holdings', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'RPD', category: 'cybersecurity', companyName: 'Rapid7', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'VRNS', category: 'cybersecurity', companyName: 'Varonis Systems', sector: 'Technology', industry: 'Cybersecurity', exchange: 'NASDAQ', isActive: true },
    { symbol: 'AKAM', category: 'cybersecurity', companyName: 'Akamai Technologies', sector: 'Technology', industry: 'Security & CDN', exchange: 'NASDAQ', isActive: true },
    { symbol: 'DASH', category: 'consumer_internet', companyName: 'DoorDash', sector: 'Technology', industry: 'Consumer Internet', exchange: 'NASDAQ', isActive: true },
    { symbol: 'ABNB', category: 'consumer_internet', companyName: 'Airbnb', sector: 'Technology', industry: 'Consumer Internet', exchange: 'NASDAQ', isActive: true },
    { symbol: 'RBLX', category: 'consumer_internet', companyName: 'Roblox', sector: 'Technology', industry: 'Gaming', exchange: 'NYSE', isActive: true },
    { symbol: 'SPOT', category: 'consumer_internet', companyName: 'Spotify Technology', sector: 'Technology', industry: 'Streaming', exchange: 'NYSE', isActive: true },
    { symbol: 'PINS', category: 'consumer_internet', companyName: 'Pinterest', sector: 'Technology', industry: 'Social', exchange: 'NYSE', isActive: true },
    { symbol: 'SNAP', category: 'consumer_internet', companyName: 'Snap', sector: 'Technology', industry: 'Social', exchange: 'NYSE', isActive: true },
    { symbol: 'RDDT', category: 'consumer_internet', companyName: 'Reddit', sector: 'Technology', industry: 'Social', exchange: 'NYSE', isActive: true },
    { symbol: 'COIN', category: 'fintech_tech', companyName: 'Coinbase Global', sector: 'Technology', industry: 'Fintech', exchange: 'NASDAQ', isActive: true },
    { symbol: 'HOOD', category: 'fintech_tech', companyName: 'Robinhood Markets', sector: 'Technology', industry: 'Fintech', exchange: 'NASDAQ', isActive: true },
    { symbol: 'XYZ', category: 'fintech_tech', companyName: 'Block', sector: 'Technology', industry: 'Fintech', exchange: 'NYSE', isActive: true },
    { symbol: 'AFRM', category: 'fintech_tech', companyName: 'Affirm Holdings', sector: 'Technology', industry: 'Fintech', exchange: 'NASDAQ', isActive: true },
    { symbol: 'SOFI', category: 'fintech_tech', companyName: 'SoFi Technologies', sector: 'Technology', industry: 'Fintech', exchange: 'NASDAQ', isActive: true },
  ],
  signals: [
    {
      symbol: 'AMD',
      companyName: 'Advanced Micro Devices',
      score: 82,
      scoreDelta: 9,
      status: 'strong_setup',
      actionState: 'buy_review',
      lifecycleState: 'upgraded',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(25, 30, 15, 7, 5),
      close: 164.22,
      priceChange1h: 1.2,
      priceChange1d: -0.4,
      rsi: 46.4,
      previousRsi: 42.1,
      rsiDelta: 4.3,
      macdHistogram: -0.52,
      previousMacdHistogram: -0.91,
      histDelta: 0.39,
      macdState: 'Recovering',
      histogramSlope: 0.39,
      volumeRatio: 1.18,
      distanceFromLow: 4.2,
      priceVsSma20: -1.8,
      priceVsSma50: -2.6,
      priceVsSma200: 8.9,
      lastAlert: 'Strong setup',
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'buy_review',
        ['RSI is below 50 and rising', 'MACD histogram is negative but improving', 'Price is within 10% of the 60-period low', 'Volume is above the 20-period average'],
        ['MACD bullish cross has not occurred yet'],
        ['Signal is technical only and does not include earnings or news context'],
      ),
      summary: {
        rsi: 'RSI is below 50 and rising across the latest candles.',
        macd: 'MACD histogram remains negative but recovery slope is positive.',
        volume: 'Volume is above the 20-period average.',
        trend: 'Price is near the 50-period average and holding long trend support.',
        price: 'Price is 4.2% above the recent 60-period low.',
      },
    },
    {
      symbol: 'CRM',
      companyName: 'Salesforce',
      score: 77,
      scoreDelta: 6,
      status: 'strong_setup',
      actionState: 'buy_review',
      lifecycleState: 'continuing',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(20, 28, 15, 9, 5),
      close: 286.74,
      priceChange1h: 0.7,
      priceChange1d: 0.2,
      rsi: 47.2,
      previousRsi: 44.8,
      rsiDelta: 2.4,
      macdHistogram: -0.31,
      previousMacdHistogram: -0.59,
      histDelta: 0.28,
      macdState: 'Recovering',
      histogramSlope: 0.28,
      volumeRatio: 1.04,
      distanceFromLow: 5.8,
      priceVsSma20: -0.9,
      priceVsSma50: -1.4,
      priceVsSma200: 6.1,
      lastAlert: 'Upgraded',
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'buy_review',
        ['RSI is recovering below 50', 'MACD histogram is compressing toward zero', 'Price remains near the 60-period low', 'Volume is slightly above baseline'],
        ['Volume confirmation is not broad yet'],
        ['Review position sizing before adding exposure'],
      ),
      summary: {
        rsi: 'RSI is recovering but still below neutral.',
        macd: 'Negative histogram is compressing toward zero.',
        volume: 'Volume is slightly above baseline.',
        trend: 'Price remains close to the 50-period average.',
        price: 'Price is still within the local reset zone.',
      },
    },
    {
      symbol: 'ADBE',
      companyName: 'Adobe',
      score: 66,
      scoreDelta: 4,
      status: 'watchlist_setup',
      actionState: 'watch',
      lifecycleState: 'unchanged',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(15, 20, 15, 6, 10),
      close: 421.36,
      priceChange1h: -0.2,
      priceChange1d: -1.1,
      rsi: 39.8,
      previousRsi: 38.9,
      rsiDelta: 0.9,
      macdHistogram: -1.22,
      previousMacdHistogram: -1.26,
      histDelta: 0.04,
      macdState: 'Flat',
      histogramSlope: 0.04,
      volumeRatio: 0.93,
      distanceFromLow: 7.9,
      priceVsSma20: -4.2,
      priceVsSma50: -6.8,
      priceVsSma200: -1.8,
      lastAlert: null,
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'watch',
        ['RSI is below 50', 'Price is near the recent low', 'Histogram has stopped deteriorating'],
        ['Trend safety remains below the 200-period average', 'Volume is not confirming'],
        ['Keep as watchlist only until trend improves'],
      ),
      summary: {
        rsi: 'RSI has lifted but recovery is early.',
        macd: 'Histogram is flat-to-improving after a deep negative print.',
        volume: 'Volume is stable but not confirming.',
        trend: 'Price is still below the 50-period average.',
        price: 'Price remains close enough to the local low to monitor.',
      },
    },
    {
      symbol: 'NVDA',
      companyName: 'Nvidia',
      score: 54,
      scoreDelta: -12,
      status: 'overextended',
      actionState: 'do_not_add',
      lifecycleState: 'downgraded',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(5, 14, 5, 15, 15),
      close: 122.84,
      priceChange1h: -0.8,
      priceChange1d: -2.3,
      rsi: 55.1,
      previousRsi: 56.4,
      rsiDelta: -1.3,
      macdHistogram: 0.26,
      previousMacdHistogram: 0.31,
      histDelta: -0.05,
      macdState: 'Weakening',
      histogramSlope: -0.05,
      volumeRatio: 0.88,
      distanceFromLow: 13.2,
      priceVsSma20: 2.1,
      priceVsSma50: 4.9,
      priceVsSma200: 22.7,
      lastAlert: 'Score drop',
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'do_not_add',
        ['Long trend remains intact', 'Price is still above major moving averages'],
        ['RSI is outside recovery band', 'MACD histogram is fading', 'Price is extended from the recent low'],
        ['Avoid adding until reset conditions return'],
      ),
      summary: {
        rsi: 'RSI is above the recovery zone and softening.',
        macd: 'Histogram is positive but fading.',
        volume: 'Volume is under the 20-period average.',
        trend: 'Trend remains constructive but not in reset.',
        price: 'Price is not near enough to the local low.',
      },
    },
    {
      symbol: 'PANW',
      companyName: 'Palo Alto Networks',
      score: 58,
      scoreDelta: 6,
      status: 'watchlist_setup',
      actionState: 'watch',
      lifecycleState: 'upgraded',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(20, 22, 10, 1, 5),
      close: 296.4,
      priceChange1h: 0.6,
      priceChange1d: -0.7,
      rsi: 43.8,
      previousRsi: 41.5,
      rsiDelta: 2.3,
      macdHistogram: -0.37,
      previousMacdHistogram: -0.58,
      histDelta: 0.21,
      macdState: 'Recovering',
      histogramSlope: 0.21,
      volumeRatio: 0.91,
      distanceFromLow: 6.4,
      priceVsSma20: -2.4,
      priceVsSma50: -3.2,
      priceVsSma200: 11.1,
      lastAlert: null,
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'watch',
        ['RSI is in the recovery band', 'MACD histogram slope is positive', 'Price is within 10% of the 60-period low'],
        ['Volume ratio is still below 1.0x', 'Final score has not cleared watchlist threshold'],
        ['Keep alerts quiet unless score clears the backend threshold'],
      ),
      summary: {
        rsi: 'RSI is in the recovery band and moving higher.',
        macd: 'Histogram remains negative but the slope has improved.',
        volume: 'Volume is not yet confirming above baseline.',
        trend: 'Long trend remains intact above the 200-period average.',
        price: 'Price is within 6.4% of the recent 60-period low.',
      },
    },
    {
      symbol: 'SNOW',
      companyName: 'Snowflake',
      score: 59,
      scoreDelta: 7,
      status: 'watchlist_setup',
      actionState: 'watch',
      lifecycleState: 'upgraded',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(20, 22, 10, 2, 5),
      close: 134.2,
      priceChange1h: 1.0,
      priceChange1d: -0.9,
      rsi: 41.6,
      previousRsi: 38.7,
      rsiDelta: 2.9,
      macdHistogram: -0.84,
      previousMacdHistogram: -1.08,
      histDelta: 0.24,
      macdState: 'Recovering',
      histogramSlope: 0.24,
      volumeRatio: 0.86,
      distanceFromLow: 4.8,
      priceVsSma20: -3.7,
      priceVsSma50: -7.4,
      priceVsSma200: -2.2,
      lastAlert: null,
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'watch',
        ['RSI is below 50 and rising', 'MACD histogram is negative but improving', 'Price is close to the target zone'],
        ['Price remains below the 200-period average', 'Volume ratio is below confirmation'],
        ['Watchlist trigger is approaching but not active'],
      ),
      summary: {
        rsi: 'RSI is below 50 and recovering from reset territory.',
        macd: 'Negative histogram is improving but remains deep.',
        volume: 'Volume sits below confirmation threshold.',
        trend: 'Price still needs to reclaim the 200-period average.',
        price: 'Price is close to the recent low and target zone.',
      },
    },
    {
      symbol: 'AVGO',
      companyName: 'Broadcom',
      score: 48,
      scoreDelta: -9,
      status: 'weakening',
      actionState: 'do_not_add',
      lifecycleState: 'downgraded',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(0, 18, 0, 15, 15),
      close: 1468.3,
      priceChange1h: -1.4,
      priceChange1d: -2.0,
      rsi: 61.3,
      previousRsi: 64.9,
      rsiDelta: -3.6,
      macdHistogram: 0.18,
      previousMacdHistogram: 0.44,
      histDelta: -0.26,
      macdState: 'Weakening',
      histogramSlope: -0.26,
      volumeRatio: 1.21,
      distanceFromLow: 18.6,
      priceVsSma20: 1.6,
      priceVsSma50: 7.9,
      priceVsSma200: 28.5,
      lastAlert: 'Weakening',
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'do_not_add',
        ['Long trend is intact above major moving averages'],
        ['RSI is rolling down', 'MACD histogram is weakening', 'Price is extended from the recent low'],
        ['Elevated volume on weakening move requires review'],
      ),
      summary: {
        rsi: 'RSI is above reset range and rolling down.',
        macd: 'Positive histogram is losing slope quickly.',
        volume: 'Volume is elevated during the weakening move.',
        trend: 'Price is still above all major moving averages.',
        price: 'Price is extended from the recent low.',
      },
    },
    {
      symbol: 'MSFT',
      companyName: 'Microsoft',
      score: 44,
      scoreDelta: 1,
      status: 'no_signal',
      actionState: 'hold',
      lifecycleState: 'unchanged',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(5, 9, 0, 15, 15),
      close: 426.55,
      priceChange1h: 0.1,
      priceChange1d: 0.4,
      rsi: 52.8,
      previousRsi: 52.1,
      rsiDelta: 0.7,
      macdHistogram: 0.05,
      previousMacdHistogram: 0.04,
      histDelta: 0.01,
      macdState: 'Flat',
      histogramSlope: 0.01,
      volumeRatio: 0.78,
      distanceFromLow: 12.7,
      priceVsSma20: 0.7,
      priceVsSma50: 2.9,
      priceVsSma200: 14.8,
      lastAlert: null,
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'hold',
        ['Long trend is constructive'],
        ['RSI is outside the recovery band', 'MACD is flat', 'Volume is below average'],
        ['No backend signal state requires action'],
      ),
      summary: {
        rsi: 'RSI is above the target recovery band.',
        macd: 'Histogram is flat with limited momentum change.',
        volume: 'Volume is below baseline.',
        trend: 'Trend is constructive but not in a reset setup.',
        price: 'Price is not close enough to the recent low.',
      },
    },
    {
      symbol: 'CRWD',
      companyName: 'CrowdStrike',
      score: 52,
      scoreDelta: 1,
      status: 'no_signal',
      actionState: 'hold',
      lifecycleState: 'unchanged',
      signalType: 'momentum_recovery',
      scoreBreakdown: breakdown(5, 12, 5, 15, 15),
      close: 352.1,
      priceChange1h: -0.1,
      priceChange1d: 0.8,
      rsi: 51.2,
      previousRsi: 50.7,
      rsiDelta: 0.5,
      macdHistogram: 0.12,
      previousMacdHistogram: 0.10,
      histDelta: 0.02,
      macdState: 'Flat',
      histogramSlope: 0.02,
      volumeRatio: 0.74,
      distanceFromLow: 11.3,
      priceVsSma20: 1.1,
      priceVsSma50: 3.8,
      priceVsSma200: 19.4,
      lastAlert: null,
      lastUpdated: '2026-06-02T20:00:00Z',
      explanation: explanation(
        'hold',
        ['Long trend remains intact', 'Score is stable'],
        ['RSI has not reset into range', 'Volume is below confirmation', 'Signal score is below watchlist threshold'],
        ['Wait for backend trigger state before alerting'],
      ),
      summary: {
        rsi: 'RSI has not reset into the preferred range.',
        macd: 'Histogram is positive but not accelerating.',
        volume: 'Volume remains below confirmation threshold.',
        trend: 'Long trend is intact.',
        price: 'Price is outside the near-low recovery zone.',
      },
    },
  ],
  portfolio: [
    {
      symbol: 'NVDA',
      quantity: 120,
      averagePrice: 104.1,
      currentPrice: 122.84,
      marketValue: 14740.8,
      unrealisedPnl: 2248.8,
      unrealisedPnlPercent: 18.0,
      portfolioWeight: 34.4,
      signalScore: 54,
      scoreDelta: -12,
      signalStatus: 'overextended',
      actionState: 'do_not_add',
      rsi: 55.1,
      macdState: 'Weakening',
      riskState: 'overextended',
      suggestedAction: 'Hold / avoid adding',
      explanation: explanation(
        'do_not_add',
        ['Position is profitable', 'Long trend remains intact'],
        ['Backend signal status is overextended', 'Score dropped by 12', 'MACD histogram is fading'],
        ['Avoid adding while signal state weakens'],
      ),
    },
    {
      symbol: 'AMD',
      quantity: 80,
      averagePrice: 169.7,
      currentPrice: 164.22,
      marketValue: 13137.6,
      unrealisedPnl: -438.4,
      unrealisedPnlPercent: -3.2,
      portfolioWeight: 30.6,
      signalScore: 82,
      scoreDelta: 9,
      signalStatus: 'strong_setup',
      actionState: 'buy_review',
      rsi: 46.4,
      macdState: 'Recovering',
      riskState: 'opportunity',
      suggestedAction: 'Add Review',
      explanation: explanation(
        'buy_review',
        ['Backend signal status upgraded to Strong Setup', 'RSI is recovering below 50', 'MACD histogram is improving'],
        ['Position is currently below cost base'],
        ['Review allocation before increasing exposure'],
      ),
    },
    {
      symbol: 'CRM',
      quantity: 35,
      averagePrice: 271.5,
      currentPrice: 286.74,
      marketValue: 10035.9,
      unrealisedPnl: 533.4,
      unrealisedPnlPercent: 5.6,
      portfolioWeight: 23.4,
      signalScore: 77,
      scoreDelta: 6,
      signalStatus: 'strong_setup',
      actionState: 'buy_review',
      rsi: 47.2,
      macdState: 'Recovering',
      riskState: 'neutral',
      suggestedAction: 'Hold / Buy Review',
      explanation: explanation(
        'buy_review',
        ['Backend signal status is Strong Setup', 'Position is profitable', 'RSI remains in recovery range'],
        ['Volume confirmation is moderate'],
        ['Hold existing position; review add only if target allocation allows'],
      ),
    },
  ],
  watchlist: [
    {
      symbol: 'SNOW',
      companyName: 'Snowflake',
      category: 'Data Cloud',
      targetBuyZone: 128,
      currentPrice: 134.2,
      distanceToTarget: 4.8,
      signalScore: 59,
      scoreDelta: 7,
      signalStatus: 'watchlist_setup',
      triggerState: 'approaching',
      targetSignalScore: 75,
      rsi: 41.6,
      macdHistogram: -0.84,
      volumeRatio: 0.86,
      alertStatus: 'Near trigger',
      notes: 'Notify if score clears 75 and price returns below 130.',
      explanation: explanation(
        'watch',
        ['Watchlist overlay is approaching', 'Price is within 5% of target zone', 'Score rose by 7'],
        ['Score has not reached target signal score', 'Price condition is not fully met'],
        ['No watchlist alert until backend trigger state becomes triggered'],
      ),
    },
    {
      symbol: 'PANW',
      companyName: 'Palo Alto Networks',
      category: 'Cybersecurity',
      targetBuyZone: 285,
      currentPrice: 296.4,
      distanceToTarget: 4.0,
      signalScore: 58,
      scoreDelta: 6,
      signalStatus: 'watchlist_setup',
      triggerState: 'approaching',
      targetSignalScore: 75,
      rsi: 43.8,
      macdHistogram: -0.37,
      volumeRatio: 0.91,
      alertStatus: 'Building',
      notes: 'Watch for histogram recovery and volume above 1.0x.',
      explanation: explanation(
        'watch',
        ['Signal score is within 17 points of target', 'RSI is in recovery band', 'MACD histogram is rising'],
        ['Volume ratio is below 1.0x', 'Price remains above target zone'],
        ['Keep in watchlist queue'],
      ),
    },
    {
      symbol: 'CRWD',
      companyName: 'CrowdStrike',
      category: 'Cybersecurity',
      targetBuyZone: 335,
      currentPrice: 352.1,
      distanceToTarget: 5.1,
      signalScore: 52,
      scoreDelta: 1,
      signalStatus: 'no_signal',
      triggerState: 'not_ready',
      targetSignalScore: 75,
      rsi: 51.2,
      macdHistogram: 0.12,
      volumeRatio: 0.74,
      alertStatus: 'Dormant',
      notes: 'Wait for RSI reset below 50.',
      explanation: explanation(
        'hold',
        ['Ticker remains active on watchlist'],
        ['Score is below target', 'RSI has not reset below 50', 'Volume ratio is below threshold'],
        ['No alert should fire from current backend state'],
      ),
    },
  ],
  signalChanges: [
    { symbol: 'AMD', change: 9, label: 'upgraded to Strong Setup', status: 'improving', at: '2026-06-02T20:00:00Z' },
    { symbol: 'CRM', change: 6, label: 'score rising, now Strong', status: 'improving', at: '2026-06-02T20:00:00Z' },
    { symbol: 'NVDA', change: -12, label: 'score dropped after histogram faded', status: 'weakening', at: '2026-06-02T20:00:00Z' },
    { symbol: 'ADBE', change: 4, label: 'watchlist recovery early', status: 'neutral', at: '2026-06-02T20:00:00Z' },
  ],
  alerts: [
    {
      symbol: 'AMD',
      channel: 'telegram',
      alertType: 'strong_setup',
      message: 'AMD strong setup forming. Score 82/100. RSI and MACD histogram are both recovering while price remains near the recent low.',
      score: 82,
      previousScore: 73,
      payload: {
        action_state: 'buy_review',
        lifecycle_state: 'upgraded',
        duplicate_window_hours: 6,
      },
      sentStatus: 'sent',
      sentAt: '2026-06-02T20:00:31Z',
      createdAt: '2026-06-02T20:00:31Z',
    },
    {
      symbol: 'CRM',
      channel: 'telegram',
      alertType: 'strong_setup',
      message: 'CRM upgraded to strong setup. Score 77/100 after MACD histogram improvement and steady volume confirmation.',
      score: 77,
      previousScore: 71,
      payload: {
        action_state: 'buy_review',
        lifecycle_state: 'continuing',
        duplicate_window_hours: 6,
      },
      sentStatus: 'sent',
      sentAt: '2026-06-02T20:00:33Z',
      createdAt: '2026-06-02T20:00:33Z',
    },
    {
      symbol: 'ADBE',
      channel: 'dashboard',
      alertType: 'watchlist_setup',
      message: 'ADBE is on watchlist only. Histogram has stabilized but volume and trend confirmation remain incomplete.',
      score: 66,
      previousScore: 62,
      payload: {
        action_state: 'watch',
        skipped_reason: 'watchlist_alerts_disabled',
      },
      sentStatus: 'skipped',
      sentAt: null,
      createdAt: '2026-06-02T20:00:34Z',
    },
  ],
  scoreHistory: [
    { label: '6h ago', score: 42, rsi: 35.5, histogram: -1.48 },
    { label: '5h ago', score: 47, rsi: 36.9, histogram: -1.36 },
    { label: '4h ago', score: 53, rsi: 38.4, histogram: -1.19 },
    { label: '3h ago', score: 59, rsi: 40.7, histogram: -1.02 },
    { label: '2h ago', score: 68, rsi: 42.1, histogram: -0.91 },
    { label: '1h ago', score: 75, rsi: 44.7, histogram: -0.69 },
    { label: 'Now', score: 82, rsi: 46.4, histogram: -0.52 },
  ],
};
