"""
Regenerate `src/lib/emerging-winner/demo.ts` from the REAL engine, so the demo fallback can never
drift from real engine output (its header has always claimed this; the generator now actually exists -
the 2026-08-01 audit found the file was hand-pinned to a pre-champion engine state).

    .venv/bin/python -m workers.emerging_winner.gen_demo

Deterministic: fixed generated_at, the illustrative candidate set, the deployed champion artifact.
Rerun whenever the engine's scoring semantics or the champion artifact change.
"""
from __future__ import annotations

import json
import os

from .engine import ENGINE_VERSION, rank_universe
from .main import ILLUSTRATIVE_CANDIDATES

GENERATED_AT = "2026-08-01T00:00:00+00:00"  # fixed for reproducibility - bump when regenerating
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "src", "lib", "emerging-winner", "demo.ts")

HEADER = '''/**
 * Demo fallback for the Emerging Winner Engine surface, used when Supabase is not configured or the
 * ledger is empty. GENERATED from the Python engine (rank_universe over the illustrative candidates)
 * so it can never drift from real engine output.
 * Regenerate: .venv/bin/python -m workers.emerging_winner.gen_demo
 * Illustrative data, not live market data.
 */
import type { EmergingWinnerQueue } from './types';

export const DEMO_QUEUE: EmergingWinnerQueue = '''


def build_queue() -> dict:
    results = rank_universe(ILLUSTRATIVE_CANDIDATES, generated_at=GENERATED_AT)
    return {
        "queue": [r.to_dict() for r in results],
        "generated_at": GENERATED_AT,
        "engine_version": ENGINE_VERSION,
        "demo": True,
        "note": (
            "Illustrative demo output generated by the real engine over the illustrative candidate "
            "set. Not live market data."
        ),
    }


def main() -> int:
    queue = build_queue()
    out = os.path.abspath(OUT_PATH)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write(json.dumps(queue, indent=2))
        fh.write(";\n")
    print(f"gen_demo: wrote {len(queue['queue'])} results -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
