/**
 * Typed loader for src/lib/generated/model-evidence.json - the machine-written record of what
 * stands behind the model numbers shown on /models. The JSON is regenerated by the backtest
 * `record` step after every eval cycle; this module only types and null-safes it. Nothing here
 * invents a number: every field either comes straight from the artifact or is null, and the
 * Evidence surface omits whatever is missing rather than papering over it.
 */

import rawEvidence from '@/lib/generated/model-evidence.json';

export interface EvidenceCorpus {
  sha256: string | null;
  dataEnd: string | null;
  rows: number | null;
  curatedRows: number | null;
  symbols: number | null;
  baseRate: number | null;
  holdoutStart: string | null;
  label: string | null;
}

export interface EvidenceVerdict {
  model: string;
  label: string;
  split: string;
  /** promoted | refuted | refuted_as_ranker (kept open for future statuses). */
  status: string;
  lift: number;
  ci90: [number, number];
  rocAuc: number | null;
  ece: number | null;
  precisionAtK: number | null;
  baseRate: number | null;
  n: number | null;
  worstCohort: number | null;
}

export interface KScanEntry {
  precision: number;
  k: number;
  lift: number;
}

export interface CalibrationBin {
  bin: number;
  predicted: number;
  actual: number;
  n: number;
}

export interface CohortRow {
  cohort: string;
  precision_at_k: number;
  k: number;
  n: number;
  base_rate: number;
  expected_hits_null: number;
}

export interface EvidenceWeights {
  features: string[];
  current: number[];
  baselineSynthetic: number[];
  note: string | null;
}

export interface LeakageStep {
  label: string;
  lift: number;
  note: string | null;
  confirm: boolean;
}

export interface DeploymentRestatement {
  base: number;
  precision: number;
  note: string | null;
}

export interface LabelDiagnostics {
  option4ExcludedStillListed: number | null;
  option4ExcludedLiquidity: number | null;
  note: string | null;
}

export interface EvidencePromotion {
  forcedOverFloor: boolean;
  reason: string | null;
  promotedOver: string | null;
}

export interface GradeDimension {
  dimension: string;
  grade: string;
  why: string;
}

export interface EvidenceGrades {
  gradedAtCorpus: string | null;
  dimensions: GradeDimension[];
}

export interface ModelEvidence {
  generatedFromCorpus: EvidenceCorpus | null;
  caveat: string | null;
  verdict: EvidenceVerdict[];
  kScan: Record<string, KScanEntry> | null;
  calibration: Record<string, CalibrationBin[]> | null;
  cohorts: { dev: CohortRow[]; holdout: CohortRow[] } | null;
  weights: EvidenceWeights | null;
  leakage: LeakageStep[];
  deploymentRestatement: DeploymentRestatement | null;
  labelDiagnostics: LabelDiagnostics | null;
  promotion: EvidencePromotion | null;
  grades: EvidenceGrades | null;
  evidenceDocs: string[];
}

/* ------------------------------- narrowing helpers ------------------------------- */

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function num(v: unknown): number | null {
  return typeof v === 'number' && Number.isFinite(v) ? v : null;
}

function str(v: unknown): string | null {
  return typeof v === 'string' && v.length > 0 ? v : null;
}

function numArray(v: unknown): number[] | null {
  if (!Array.isArray(v)) return null;
  const out: number[] = [];
  for (const x of v) {
    const n = num(x);
    if (n === null) return null;
    out.push(n);
  }
  return out;
}

function strArray(v: unknown): string[] {
  if (!Array.isArray(v)) return [];
  return v.filter((x): x is string => typeof x === 'string' && x.length > 0);
}

/* ------------------------------- section parsers ------------------------------- */

function parseCorpus(v: unknown): EvidenceCorpus | null {
  if (!isRecord(v)) return null;
  return {
    sha256: str(v.sha256),
    dataEnd: str(v.dataEnd),
    rows: num(v.rows),
    curatedRows: num(v.curatedRows),
    symbols: num(v.symbols),
    baseRate: num(v.baseRate),
    holdoutStart: str(v.holdoutStart),
    label: str(v.label),
  };
}

function parseVerdict(v: unknown): EvidenceVerdict | null {
  if (!isRecord(v)) return null;
  const model = str(v.model);
  const label = str(v.label);
  const split = str(v.split);
  const status = str(v.status);
  const lift = num(v.lift);
  const ci = numArray(v.ci90);
  if (!model || !label || !split || !status || lift === null || !ci || ci.length !== 2) return null;
  return {
    model,
    label,
    split,
    status,
    lift,
    ci90: [ci[0], ci[1]],
    rocAuc: num(v.rocAuc),
    ece: num(v.ece),
    precisionAtK: num(v.precisionAtK),
    baseRate: num(v.baseRate),
    n: num(v.n),
    worstCohort: num(v.worstCohort),
  };
}

function parseKScan(v: unknown): Record<string, KScanEntry> | null {
  if (!isRecord(v)) return null;
  const out: Record<string, KScanEntry> = {};
  for (const [key, entry] of Object.entries(v)) {
    if (!isRecord(entry)) continue;
    const precision = num(entry.precision);
    const k = num(entry.k);
    const lift = num(entry.lift);
    if (precision === null || k === null || lift === null) continue;
    out[key] = { precision, k, lift };
  }
  return Object.keys(out).length ? out : null;
}

function parseCalibrationBins(v: unknown): CalibrationBin[] {
  if (!Array.isArray(v)) return [];
  const out: CalibrationBin[] = [];
  for (const b of v) {
    if (!isRecord(b)) continue;
    const bin = num(b.bin);
    const predicted = num(b.predicted);
    const actual = num(b.actual);
    const n = num(b.n);
    if (bin === null || predicted === null || actual === null || n === null) continue;
    out.push({ bin, predicted, actual, n });
  }
  return out;
}

function parseCalibration(v: unknown): Record<string, CalibrationBin[]> | null {
  if (!isRecord(v)) return null;
  const out: Record<string, CalibrationBin[]> = {};
  for (const [key, bins] of Object.entries(v)) {
    const parsed = parseCalibrationBins(bins);
    if (parsed.length) out[key] = parsed;
  }
  return Object.keys(out).length ? out : null;
}

function parseCohortRows(v: unknown): CohortRow[] {
  if (!Array.isArray(v)) return [];
  const out: CohortRow[] = [];
  for (const c of v) {
    if (!isRecord(c)) continue;
    const cohort = str(c.cohort);
    const precision = num(c.precision_at_k);
    const k = num(c.k);
    const n = num(c.n);
    const baseRate = num(c.base_rate);
    const expected = num(c.expected_hits_null);
    if (!cohort || precision === null || k === null || n === null || baseRate === null || expected === null) continue;
    out.push({ cohort, precision_at_k: precision, k, n, base_rate: baseRate, expected_hits_null: expected });
  }
  return out;
}

function parseCohorts(v: unknown): { dev: CohortRow[]; holdout: CohortRow[] } | null {
  if (!isRecord(v)) return null;
  const dev = parseCohortRows(v.dev);
  const holdout = parseCohortRows(v.holdout);
  if (!dev.length && !holdout.length) return null;
  return { dev, holdout };
}

function parseWeights(v: unknown): EvidenceWeights | null {
  if (!isRecord(v)) return null;
  const features = strArray(v.features);
  const current = numArray(v.current);
  const baselineSynthetic = numArray(v.baselineSynthetic);
  if (!features.length || !current || !baselineSynthetic) return null;
  if (current.length !== features.length || baselineSynthetic.length !== features.length) return null;
  return { features, current, baselineSynthetic, note: str(v.note) };
}

function parseLeakage(v: unknown): LeakageStep[] {
  if (!Array.isArray(v)) return [];
  const out: LeakageStep[] = [];
  for (const s of v) {
    if (!isRecord(s)) continue;
    const label = str(s.label);
    const lift = num(s.lift);
    if (!label || lift === null) continue;
    out.push({ label, lift, note: str(s.note), confirm: s.confirm === true });
  }
  return out;
}

function parseDeploymentRestatement(v: unknown): DeploymentRestatement | null {
  if (!isRecord(v)) return null;
  const base = num(v.base);
  const precision = num(v.precision);
  if (base === null || precision === null) return null;
  return { base, precision, note: str(v.note) };
}

function parseLabelDiagnostics(v: unknown): LabelDiagnostics | null {
  if (!isRecord(v)) return null;
  const parsed: LabelDiagnostics = {
    option4ExcludedStillListed: num(v.option4_excluded_still_listed),
    option4ExcludedLiquidity: num(v.option4_excluded_liquidity),
    note: str(v.note),
  };
  if (parsed.option4ExcludedStillListed === null && parsed.option4ExcludedLiquidity === null && !parsed.note) return null;
  return parsed;
}

function parsePromotion(v: unknown): EvidencePromotion | null {
  if (!isRecord(v)) return null;
  const parsed: EvidencePromotion = {
    forcedOverFloor: v.forced_over_floor === true,
    reason: str(v.reason),
    promotedOver: str(v.promoted_over),
  };
  if (!parsed.reason && !parsed.promotedOver) return null;
  return parsed;
}

function parseGrades(v: unknown): EvidenceGrades | null {
  if (!isRecord(v)) return null;
  const dims: GradeDimension[] = [];
  if (Array.isArray(v.dimensions)) {
    for (const d of v.dimensions) {
      if (!isRecord(d)) continue;
      const dimension = str(d.dimension);
      const grade = str(d.grade);
      const why = str(d.why);
      if (!dimension || !grade || !why) continue;
      dims.push({ dimension, grade, why });
    }
  }
  if (!dims.length) return null;
  return { gradedAtCorpus: str(v.graded_at_corpus), dimensions: dims };
}

/* ------------------------------- public API ------------------------------- */

/**
 * Normalise an untyped evidence payload into the null-safe ModelEvidence shape. Exported so tests
 * can build minimal or degraded payloads and pin that the surface never crashes on missing fields.
 */
export function normaliseModelEvidence(raw: unknown): ModelEvidence {
  const r = isRecord(raw) ? raw : {};
  const verdicts = Array.isArray(r.verdict)
    ? r.verdict.map(parseVerdict).filter((v): v is EvidenceVerdict => v !== null)
    : [];
  return {
    generatedFromCorpus: parseCorpus(r.generatedFromCorpus),
    caveat: str(r.caveat),
    verdict: verdicts,
    kScan: parseKScan(r.kScan),
    calibration: parseCalibration(r.calibration),
    cohorts: parseCohorts(r.cohorts),
    weights: parseWeights(r.weights),
    leakage: parseLeakage(r.leakage),
    deploymentRestatement: parseDeploymentRestatement(r.deploymentRestatement),
    labelDiagnostics: parseLabelDiagnostics(r.labelDiagnostics),
    promotion: parsePromotion(r.promotion),
    grades: parseGrades(r.grades),
    evidenceDocs: strArray(r.evidenceDocs),
  };
}

/** Load the checked-in evidence artifact (statically imported, same pattern as the other generated JSON). */
export function loadModelEvidence(): ModelEvidence {
  return normaliseModelEvidence(rawEvidence);
}
