/**
 * Lyra -> Pine Script v5 strategy generator.
 *
 * This turns Lyra's deterministic oversold-recovery score into a Pine v5 strategy you can
 * paste into TradingView and backtest. It is a faithful mirror of the scanner's scoring math,
 * so the strategy you backtest in TradingView is the same logic that surfaces a Finding here.
 *
 * SOURCE OF TRUTH: workers/stock_scanner/signal_engine.py (calculate_score) plus the indicator
 * definitions in workers/stock_scanner/indicators.py. If a weight or band changes there, change
 * LYRA_SCORE_MODEL below and the parity test in __tests__/lyra-strategy.test.ts will hold both
 * sides honest.
 *
 * The AI never invents a number: every point here comes from the same deterministic rules the
 * engine uses. Research only - not financial advice.
 */

import { APP_VERSION } from '@/lib/version';

/**
 * The exact weights, bands and thresholds of Lyra's score. Caps: RSI 25, MACD 30, price 15,
 * trend 15, volume 15 -> 100 max. Mirrors signal_engine.py::calculate_score.
 */
export const LYRA_SCORE_MODEL = {
  rsi: {
    // RSI(14) sitting in the reset band, rising over 1 and 2 periods. Cap 25.
    bandLow: 35,
    bandHigh: 50,
    bandPts: 10,
    rising1Pts: 10,
    rising2Pts: 5,
  },
  macd: {
    // Histogram negative but improving, with a below-signal-while-improving bonus. Cap 30.
    negativePts: 8,
    improving1Pts: 12,
    improving2Pts: 5,
    belowSignalImprovingPts: 5,
  },
  price: {
    // Price pinned near the 60-period low and near/below the 50 SMA. Cap 15.
    lowLookback: 60,
    lowDistancePct: 10,
    lowDistancePts: 10,
    nearSma50Mult: 1.03,
    nearSma50Pts: 5,
  },
  trend: {
    // Long-trend posture (the two SMA200 terms are mutually exclusive) plus SMA20-vs-SMA50. Cap 15.
    aboveSma200Pts: 10,
    nearSma200Mult: 0.95,
    nearSma200Pts: 5,
    sma20VsSma50Mult: 0.95,
    sma20VsSma50Pts: 5,
  },
  volume: {
    // Volume confirmation in three steps. Cap 15.
    ratioLow: 0.8,
    ratioLowPts: 5,
    ratioHigh: 1.0,
    ratioHighPts: 5,
    risingPts: 5,
  },
  thresholds: {
    // assign_signal_status: >= strong is a strong_setup (entry); dropping below watchlist invalidates.
    strong: 75,
    watchlist: 60,
  },
} as const;

export interface PineStrategyOptions {
  /** Ticker the strategy is generated for, used only in the title comment. */
  symbol?: string;
  /** Entry score threshold. Defaults to Lyra's strong-setup threshold (75). */
  strongThreshold?: number;
  /** Exit-floor score threshold. Defaults to Lyra's watchlist threshold (60). */
  watchlistThreshold?: number;
}

/** Strip anything that could break the Pine title string. */
function safeSymbol(symbol: string | undefined): string {
  if (!symbol) return 'SYMBOL';
  const cleaned = symbol.replace(/[^A-Za-z0-9.:_-]/g, '').toUpperCase();
  return cleaned || 'SYMBOL';
}

/**
 * Generate a Pine v5 strategy that reproduces Lyra's deterministic oversold-recovery score.
 * Returns the full script source as a string (ready to paste into TradingView's Pine editor,
 * or to inject via the tradingview-mcp `pine_set_source` tool).
 */
export function generateLyraPineStrategy(opts: PineStrategyOptions = {}): string {
  const m = LYRA_SCORE_MODEL;
  const symbol = safeSymbol(opts.symbol);
  const strong = opts.strongThreshold ?? m.thresholds.strong;
  const watchlist = opts.watchlistThreshold ?? m.thresholds.watchlist;

  return `//@version=5
// Lyra Oversold-Recovery Strategy (v1) - generated for ${symbol}
// Mirrors Lyra's deterministic 0-100 score: an RSI(14) reset band that is rising, a still-negative
// but improving MACD histogram, price pinned near the 60-period low, trend posture and volume
// confirmation. Source of truth: workers/stock_scanner/signal_engine.py (calculate_score).
// A high score means "beaten-down name turning up", not "breaking out to new highs".
// Research only - not financial advice. Backtest results are hypothetical. Generated by Lyra v${APP_VERSION}.
strategy("Lyra Oversold-Recovery v1 - ${symbol}", overlay=false, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=10, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2, pyramiding=0, calc_on_order_fills=false)

// --- Tunable thresholds (defaults are Lyra's engine values) ---
strongTh = input.int(${strong}, "Entry: strong-setup score", minval=1, maxval=100, group="Lyra thresholds")
watchTh  = input.int(${watchlist}, "Exit floor: watchlist score", minval=1, maxval=100, group="Lyra thresholds")
useStop  = input.bool(false, "Use ATR protective stop", group="Risk (optional)")
atrLen   = input.int(14, "ATR length", minval=1, group="Risk (optional)")
atrMult  = input.float(2.5, "ATR stop multiple", minval=0.1, step=0.1, group="Risk (optional)")

// --- Indicators (identical definitions to the Lyra scanner) ---
rsi14  = ta.rsi(close, 14)
rsiD1  = rsi14 - rsi14[1]
rsiD2  = rsi14 - rsi14[2]
[macdLine, signalLine, histLine] = ta.macd(close, 12, 26, 9)
histD1 = histLine - histLine[1]
histD2 = histLine - histLine[2]
sma20  = ta.sma(close, 20)
sma50  = ta.sma(close, 50)
sma200 = ta.sma(close, 200)
volRatio = volume / ta.sma(volume, 20)
low60  = ta.lowest(low, ${m.price.lowLookback})
dist60 = (close - low60) / low60 * 100

// --- Component scores (na-guarded so early bars award nothing, matching the engine's None-skip) ---
rsiScore = (not na(rsi14) and rsi14 >= ${m.rsi.bandLow} and rsi14 <= ${m.rsi.bandHigh} ? ${m.rsi.bandPts} : 0) + (not na(rsiD1) and rsiD1 > 0 ? ${m.rsi.rising1Pts} : 0) + (not na(rsiD2) and rsiD2 > 0 ? ${m.rsi.rising2Pts} : 0)
macdScore = (not na(histLine) and histLine < 0 ? ${m.macd.negativePts} : 0) + (not na(histD1) and histD1 > 0 ? ${m.macd.improving1Pts} : 0) + (not na(histD2) and histD2 > 0 ? ${m.macd.improving2Pts} : 0) + (not na(macdLine) and not na(signalLine) and not na(histD1) and macdLine < signalLine and histD1 > 0 ? ${m.macd.belowSignalImprovingPts} : 0)
priceScore = (not na(dist60) and dist60 <= ${m.price.lowDistancePct} ? ${m.price.lowDistancePts} : 0) + (not na(sma50) and close <= sma50 * ${m.price.nearSma50Mult} ? ${m.price.nearSma50Pts} : 0)
trendScore = (not na(sma200) and close >= sma200 ? ${m.trend.aboveSma200Pts} : (not na(sma200) and close >= sma200 * ${m.trend.nearSma200Mult} ? ${m.trend.nearSma200Pts} : 0)) + (not na(sma20) and not na(sma50) and sma20 >= sma50 * ${m.trend.sma20VsSma50Mult} ? ${m.trend.sma20VsSma50Pts} : 0)
volScore = (not na(volRatio) and volRatio >= ${m.volume.ratioLow} ? ${m.volume.ratioLowPts} : 0) + (not na(volRatio) and volRatio >= ${m.volume.ratioHigh} ? ${m.volume.ratioHighPts} : 0) + (not na(volume[1]) and volume > volume[1] ? ${m.volume.risingPts} : 0)
score = math.min(rsiScore + macdScore + priceScore + trendScore + volScore, 100)

// --- Entry / exit (engine-faithful: enter on a fresh strong setup, exit when the score invalidates) ---
longCond = ta.crossover(score, strongTh)
exitCond = score < watchTh
if longCond
    strategy.entry("Lyra Long", strategy.long)
if exitCond
    strategy.close("Lyra Long", comment="score below watchlist")
if useStop and strategy.position_size > 0
    strategy.exit("Lyra Stop", "Lyra Long", stop=strategy.position_avg_price - atrMult * ta.atr(atrLen))

// --- Score oscillator pane ---
plot(score, "Lyra score", color=color.new(color.orange, 0), linewidth=2)
plot(rsiScore + macdScore, "RSI+MACD points", color=color.new(color.teal, 40), display=display.data_window)
hline(strongTh, "Strong", color=color.new(color.green, 40), linestyle=hline.style_dashed)
hline(watchTh, "Watchlist", color=color.new(color.gray, 40), linestyle=hline.style_dashed)
bgcolor(score >= strongTh ? color.new(color.green, 88) : na, title="Strong-setup zone")
`;
}
