'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { loadModelEvidence, type EvidenceVerdict, type ModelEvidence as Evidence } from '@/lib/models/evidence';

/**
 * Evidence behind these numbers - the layer that shows what actually stands behind the model
 * projections on /models. Every number is read from src/lib/generated/model-evidence.json
 * (regenerated by the backtest `record` step after each eval cycle); nothing numeric is hardcoded
 * here, and a missing field simply omits its block. Tone rules: research only, shadow-live/Beta
 * framing unchanged, and backtest lift is never presented as a live track record.
 */

const CHANCE_LIFT = 1.0; // definitional: lift is measured against chance, so the reference line sits at 1.0x

const STATUS_LABEL: Record<string, string> = {
  promoted: 'Promoted',
  refuted: 'Refuted',
  refuted_as_ranker: 'Refuted as ranker',
  challenger_not_promoted: 'Challenger - not promoted',
  challenger: 'Challenger',
};

const STATUS_STYLE: Record<string, string> = {
  promoted: 'bg-emerald-500/15 text-emerald-300 ring-1 ring-emerald-400/30',
  refuted: 'bg-rose-500/15 text-rose-300 ring-1 ring-rose-400/30',
  refuted_as_ranker: 'bg-amber-400/15 text-amber-300 ring-1 ring-amber-300/40',
  challenger_not_promoted: 'bg-sky-500/15 text-sky-300 ring-1 ring-sky-400/30',
  challenger: 'bg-sky-500/15 text-sky-300 ring-1 ring-sky-400/30',
};

const STATUS_COLOUR: Record<string, string> = {
  promoted: '#34d399',
  refuted: '#fb7185',
  refuted_as_ranker: '#fbbf24',
  challenger_not_promoted: '#7dd3fc',
  challenger: '#7dd3fc',
};

function fmtLift(v: number): string {
  return `${v.toFixed(2)}x`;
}

function fmtPct(v: number, dp = 1): string {
  return `${(v * 100).toFixed(dp)}%`;
}

function gradeColour(grade: string): string {
  const letter = grade.charAt(0).toUpperCase();
  if (letter === 'A') return 'text-emerald-300';
  if (letter === 'B') return 'text-sky-300';
  if (letter === 'C') return 'text-amber-300';
  return 'text-rose-300';
}

function StatusChip({ status }: { status: string }) {
  return (
    <span
      className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium ${STATUS_STYLE[status] ?? 'bg-white/10 text-white/60'}`}
    >
      {STATUS_LABEL[status] ?? status}
    </span>
  );
}

function Block({ title, hint, children }: { title: string; hint?: string; children: React.ReactNode }) {
  return (
    <section className="rounded-2xl border border-white/8 bg-white/[0.02] p-3">
      <div className="mb-2 flex flex-wrap items-baseline justify-between gap-2">
        <h4 className="text-[12px] font-semibold text-white/80">{title}</h4>
        {hint ? <span className="text-[10px] text-white/35">{hint}</span> : null}
      </div>
      {children}
    </section>
  );
}

/* ------------------------------- a. verdict strip ------------------------------- */

function VerdictStrip({ verdicts }: { verdicts: EvidenceVerdict[] }) {
  const holdout = verdicts.filter((v) => v.split === 'holdout');
  // Lead with real-v1, keep artifact order for the rest.
  const rows = [...holdout.filter((v) => v.model === 'real_v1'), ...holdout.filter((v) => v.model !== 'real_v1')];
  if (!rows.length) return null;

  const lo = Math.min(CHANCE_LIFT, ...rows.map((v) => v.ci90[0]));
  const hi = Math.max(CHANCE_LIFT, ...rows.map((v) => v.ci90[1]));
  const pad = (hi - lo) * 0.08 || 0.1;
  const min = lo - pad;
  const max = hi + pad;
  const x = (v: number) => ((v - min) / (max - min)) * 100;

  return (
    <Block title="Verdict on the untouched holdout" hint="interval = 90% CI · dashed line = chance (1.0x)">
      <div className="space-y-2.5">
        {rows.map((v) => {
          const colour = STATUS_COLOUR[v.status] ?? '#7dd3fc';
          return (
            <div key={`${v.model}-${v.split}`}>
              <div className="flex flex-wrap items-center gap-2">
                <span className="min-w-0 flex-1 truncate text-[12px] font-medium text-white/80">{v.label}</span>
                <StatusChip status={v.status} />
                <span className="shrink-0 font-mono text-[11px] text-white/70">
                  {fmtLift(v.lift)}
                  <span className="text-white/35"> [{v.ci90[0].toFixed(2)}, {v.ci90[1].toFixed(2)}]</span>
                </span>
              </div>
              <svg
                viewBox="0 0 100 10"
                preserveAspectRatio="none"
                className="mt-1 h-2.5 w-full"
                role="img"
                aria-label={`${v.label}: holdout lift ${fmtLift(v.lift)}, 90% CI ${v.ci90[0].toFixed(2)} to ${v.ci90[1].toFixed(2)}, chance is 1.0x`}
              >
                <line x1="0" y1="5" x2="100" y2="5" stroke="rgba(255,255,255,0.06)" strokeWidth="1" />
                <line
                  x1={x(CHANCE_LIFT)}
                  y1="0"
                  x2={x(CHANCE_LIFT)}
                  y2="10"
                  stroke="rgba(255,255,255,0.3)"
                  strokeWidth="0.5"
                  strokeDasharray="1.5 1.5"
                />
                <line x1={x(v.ci90[0])} y1="5" x2={x(v.ci90[1])} y2="5" stroke={colour} strokeOpacity="0.55" strokeWidth="2.5" />
                <rect x={x(v.lift) - 0.6} y="1.5" width="1.2" height="7" fill={colour} />
              </svg>
              {v.n != null ? (
                <p className="mt-0.5 text-[10px] text-white/30">n = {v.n.toLocaleString('en-US')} holdout rows</p>
              ) : null}
            </div>
          );
        })}
      </div>
    </Block>
  );
}

/* ------------------------------- b. key stats row ------------------------------- */

function KeyStats({ verdicts, restatement }: { verdicts: EvidenceVerdict[]; restatement: Evidence['deploymentRestatement'] }) {
  const champion = verdicts.find((v) => v.model === 'real_v1' && v.split === 'holdout');
  if (!champion) return null;
  const stats: { k: string; v: string }[] = [];
  if (champion.precisionAtK != null && champion.baseRate != null) {
    stats.push({ k: 'Holdout precision vs base', v: `${fmtPct(champion.precisionAtK)} vs ${fmtPct(champion.baseRate)}` });
  }
  if (champion.rocAuc != null) stats.push({ k: 'ROC-AUC', v: champion.rocAuc.toFixed(3) });
  if (champion.ece != null) stats.push({ k: 'ECE (calibration error)', v: champion.ece.toFixed(3) });
  if (restatement) {
    stats.push({
      k: 'Restated at deployment base',
      v: `~${fmtPct(restatement.precision)} at ${fmtPct(restatement.base, 0)} base`,
    });
  }
  if (!stats.length) return null;
  return (
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
      {stats.map((s) => (
        <div key={s.k} className="rounded-lg border border-white/5 bg-white/[0.03] px-2.5 py-2">
          <div className="text-[14px] font-bold tabular-nums text-white">{s.v}</div>
          <div className="mt-0.5 text-[10px] leading-tight text-white/40">{s.k}</div>
        </div>
      ))}
    </div>
  );
}

/* ------------------------------- c. what the model learned ------------------------------- */

function SignedBar({ value, maxAbs, colourPos, colourNeg }: { value: number; maxAbs: number; colourPos: string; colourNeg: string }) {
  const width = maxAbs > 0 ? (Math.abs(value) / maxAbs) * 50 : 0;
  const left = value >= 0 ? 50 : 50 - width;
  return (
    <div className="relative h-1.5 w-full overflow-hidden rounded-full bg-white/[0.06]">
      <div className="absolute inset-y-0 left-1/2 w-px bg-white/15" />
      <div className={`absolute inset-y-0 rounded-full ${value >= 0 ? colourPos : colourNeg}`} style={{ left: `${left}%`, width: `${width}%` }} />
    </div>
  );
}

function LearnedWeights({ weights }: { weights: NonNullable<Evidence['weights']> }) {
  const maxAbs = Math.max(...weights.current.map(Math.abs), ...weights.baselineSynthetic.map(Math.abs), 0);
  return (
    <Block title="What the model learned" hint="synthetic hypothesis vs learned from real outcomes">
      <div className="space-y-2">
        {weights.features.map((f, i) => {
          const syn = weights.baselineSynthetic[i];
          const cur = weights.current[i];
          const dead = cur === 0;
          return (
            <div key={f} className="flex items-center gap-2">
              <span className="w-24 shrink-0 truncate text-[11px] text-white/55">{f.replace(/_/g, ' ')}</span>
              <div className="min-w-0 flex-1 space-y-0.5">
                <SignedBar value={syn} maxAbs={maxAbs} colourPos="bg-sky-400/50" colourNeg="bg-sky-400/35" />
                {dead ? (
                  <div className="flex h-1.5 items-center">
                    <span className="rounded bg-amber-400/10 px-1 text-[8px] font-medium uppercase tracking-wide leading-none text-amber-300/80">
                      unbuilt
                    </span>
                  </div>
                ) : (
                  <SignedBar value={cur} maxAbs={maxAbs} colourPos="bg-emerald-400/70" colourNeg="bg-rose-400/60" />
                )}
              </div>
              <span className="w-24 shrink-0 text-right font-mono text-[10px] text-white/45">
                {syn.toFixed(2)} / {dead ? '0' : cur.toFixed(2)}
              </span>
            </div>
          );
        })}
      </div>
      <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-white/35">
        <span>
          <span className="mr-1 inline-block h-1.5 w-3 rounded-full bg-sky-400/50 align-middle" /> synthetic hypothesis
        </span>
        <span>
          <span className="mr-1 inline-block h-1.5 w-3 rounded-full bg-emerald-400/70 align-middle" /> learned from real (rose = negative)
        </span>
      </div>
      {weights.note ? <p className="mt-2 text-[11px] leading-relaxed text-white/45">{weights.note}</p> : null}
    </Block>
  );
}

/* ------------------------------- d. how the number was earned ------------------------------- */

function LeakageSteps({ steps }: { steps: NonNullable<Evidence['leakage']> }) {
  if (!steps.length) return null;
  return (
    <Block title="How the number was earned" hint="each leak found, named and removed">
      <ol className="space-y-1.5">
        {steps.map((s, i) => (
          <li
            key={s.label}
            className={`flex flex-wrap items-baseline gap-2 rounded-lg border px-2.5 py-1.5 ${
              s.confirm ? 'border-emerald-400/25 bg-emerald-500/[0.05]' : 'border-white/5 bg-white/[0.02]'
            }`}
          >
            <span className="font-mono text-[10px] text-white/30">{i + 1}</span>
            <span className={`font-mono text-[12px] font-semibold tabular-nums ${s.confirm ? 'text-emerald-300' : 'text-white/80'}`}>
              {fmtLift(s.lift)}
            </span>
            <span className="text-[12px] text-white/70">{s.label}</span>
            {s.note ? <span className="basis-full text-[11px] text-white/40 sm:basis-auto">{s.note}</span> : null}
          </li>
        ))}
      </ol>
    </Block>
  );
}

/* ------------------------------- e. grades ------------------------------- */

function Grades({ grades }: { grades: NonNullable<Evidence['grades']> }) {
  return (
    <Block title="Report card" hint={grades.gradedAtCorpus ? `graded at corpus ${grades.gradedAtCorpus}` : undefined}>
      <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
        {grades.dimensions.map((d) => (
          <div key={d.dimension} className="rounded-lg border border-white/5 bg-white/[0.03] p-2.5">
            <div className="flex items-baseline gap-2">
              <span className={`text-lg font-bold ${gradeColour(d.grade)}`}>{d.grade}</span>
              <span className="min-w-0 flex-1 text-[11px] font-medium text-white/70">{d.dimension}</span>
            </div>
            <p className="mt-1 text-[10px] leading-relaxed text-white/45">{d.why}</p>
          </div>
        ))}
      </div>
    </Block>
  );
}

/* ------------------------------- f. caveats ------------------------------- */

function Caveats({
  caveat,
  labelDiagnostics,
  promotion,
}: {
  caveat: string | null;
  labelDiagnostics: Evidence['labelDiagnostics'];
  promotion: Evidence['promotion'];
}) {
  const [showPromotion, setShowPromotion] = useState(false);
  if (!caveat && !labelDiagnostics && !promotion) return null;
  return (
    <Block title="Caveats">
      {caveat ? (
        <p className="rounded-lg border border-amber-400/15 bg-amber-500/[0.05] px-2.5 py-2 text-[11px] leading-relaxed text-amber-200/80">
          {caveat}
        </p>
      ) : null}
      {labelDiagnostics?.note ? (
        <p className="mt-2 text-[11px] leading-relaxed text-white/50">
          {labelDiagnostics.note}
          {labelDiagnostics.option4ExcludedStillListed != null && labelDiagnostics.option4ExcludedLiquidity != null ? (
            <span className="text-white/35">
              {' '}
              (excluded by still-listed: {labelDiagnostics.option4ExcludedStillListed.toLocaleString('en-US')} · by
              liquidity: {labelDiagnostics.option4ExcludedLiquidity.toLocaleString('en-US')})
            </span>
          ) : null}
        </p>
      ) : null}
      {promotion?.reason ? (
        <div className="mt-2 rounded-lg border border-white/8 bg-white/[0.02]">
          <button
            type="button"
            onClick={() => setShowPromotion((v) => !v)}
            aria-expanded={showPromotion}
            className="flex w-full items-center justify-between px-2.5 py-2 text-left"
          >
            <span className="text-[11px] font-medium text-white/70">
              Promotion justification
              {promotion.forcedOverFloor ? (
                <span className="ml-2 rounded-full bg-amber-400/15 px-2 py-0.5 text-[9px] font-medium text-amber-300">
                  forced over floor
                </span>
              ) : null}
            </span>
            <ChevronDown size={13} className={`shrink-0 text-white/40 transition-transform ${showPromotion ? 'rotate-180' : ''}`} />
          </button>
          {showPromotion ? (
            <div className="border-t border-white/5 px-2.5 py-2">
              <p className="text-[11px] leading-relaxed text-white/60">{promotion.reason}</p>
              {promotion.promotedOver ? (
                <p className="mt-1 text-[10px] text-white/35">Promoted over: {promotion.promotedOver}</p>
              ) : null}
            </div>
          ) : null}
        </div>
      ) : null}
    </Block>
  );
}

/* ------------------------------- g. provenance footer ------------------------------- */

function ProvenanceFooter({ corpus, docs }: { corpus: Evidence['generatedFromCorpus']; docs: string[] }) {
  if (!corpus && !docs.length) return null;
  const parts: string[] = [];
  if (corpus?.sha256) parts.push(`corpus ${corpus.sha256.slice(0, 12)}`);
  if (corpus?.rows != null) parts.push(`${corpus.rows.toLocaleString('en-US')} rows`);
  if (corpus?.symbols != null) parts.push(`${corpus.symbols.toLocaleString('en-US')} symbols`);
  if (corpus?.dataEnd) parts.push(`data to ${corpus.dataEnd}`);
  if (corpus?.holdoutStart) parts.push(`holdout from ${corpus.holdoutStart}`);
  return (
    <div className="border-t border-white/5 pt-2.5">
      {parts.length ? <p className="font-mono text-[10px] text-white/35">{parts.join(' · ')}</p> : null}
      {docs.length ? (
        <div className="mt-1.5 flex flex-wrap gap-1.5">
          {docs.map((d) => (
            <code key={d} className="rounded-md bg-white/[0.04] px-1.5 py-0.5 font-mono text-[9px] text-white/40">
              {d}
            </code>
          ))}
        </div>
      ) : null}
    </div>
  );
}

/* ------------------------------- the section ------------------------------- */

export function ModelEvidence({ evidence = loadModelEvidence() }: { evidence?: Evidence }) {
  const [open, setOpen] = useState(false);
  const hasAnything =
    evidence.verdict.length > 0 ||
    evidence.weights !== null ||
    evidence.leakage.length > 0 ||
    evidence.grades !== null ||
    evidence.caveat !== null;

  return (
    <section aria-labelledby="models-evidence" className="mt-8">
      <div className="rounded-2xl border border-white/8 bg-white/[0.03]">
        <button
          type="button"
          onClick={() => setOpen((v) => !v)}
          aria-expanded={open}
          className="flex w-full items-center gap-3 px-3 py-3 text-left"
        >
          <div className="min-w-0 flex-1">
            <h3 id="models-evidence" className="text-sm font-semibold uppercase tracking-wide text-white/70">
              Evidence behind these numbers
            </h3>
            <p className="mt-1 max-w-3xl text-[12px] leading-relaxed text-white/50">
              Backtest evidence - survivor-biased corpus, research only, not a live track record.
            </p>
          </div>
          <ChevronDown size={15} className={`shrink-0 text-white/40 transition-transform ${open ? 'rotate-180' : ''}`} />
        </button>

        {open ? (
          <div className="space-y-3 border-t border-white/5 px-3 py-3">
            {!hasAnything ? (
              <p className="text-[12px] text-white/45">
                No evidence artifact is available yet. It is written by the backtest record step after each eval cycle.
              </p>
            ) : (
              <>
                <VerdictStrip verdicts={evidence.verdict} />
                <KeyStats verdicts={evidence.verdict} restatement={evidence.deploymentRestatement} />
                {evidence.weights ? <LearnedWeights weights={evidence.weights} /> : null}
                <LeakageSteps steps={evidence.leakage} />
                {evidence.grades ? <Grades grades={evidence.grades} /> : null}
                <Caveats caveat={evidence.caveat} labelDiagnostics={evidence.labelDiagnostics} promotion={evidence.promotion} />
                <ProvenanceFooter corpus={evidence.generatedFromCorpus} docs={evidence.evidenceDocs} />
              </>
            )}
          </div>
        ) : null}
      </div>
    </section>
  );
}
