'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import {
  loadModelEvidence,
  type EvidenceVerdict,
  type CohortRow,
  type CalibrationBin,
  type ModelEvidence as Evidence,
} from '@/lib/models/evidence';

/**
 * The Model Verdict - the post-run "does this model genuinely predict success?" surface. This is the
 * reveal a user sees after running a model: the full backtest evidence, in one place, wired to live
 * data. It is fully THEMED (v1.1.0 tokens): dark by default like the rest of the app, and the exact
 * light-glass render in the light theme - no raw-hex island. Chart colours use the semantic tokens
 * (positive/accent/negative) so contrast holds on both grounds; alpha blends use the -rgb channels.
 *
 * Honesty contract: every MEASURED number is read from src/lib/generated/model-evidence.json
 * (regenerated by the backtest `record` step); nothing numeric is hardcoded except the definitional
 * chance line (1.0x) and the labelled NORTH-STAR targets. A missing field omits its block. Backtest
 * lift is never presented as a live track record; surfacing stays shadow-live / Beta gated.
 */

const CHANCE_LIFT = 1.0; // definitional: lift is measured against chance, so the reference sits at 1.0x

// Semantic token colours - re-theme with the app (positive=champion, accent=held, negative=refuted).
const C = {
  champion: 'var(--lyra-positive)',
  challenger: 'var(--lyra-accent)',
  refuted: 'var(--lyra-negative)',
  nul: 'var(--lyra-ink-3)',
  ink: 'var(--lyra-ink)',
  ink2: 'var(--lyra-ink-2)',
  ink3: 'var(--lyra-ink-3)',
} as const;
// RGB-channel forms for alpha blends.
const R = {
  champion: 'var(--lyra-positive-rgb)',
  challenger: 'var(--lyra-accent-rgb)',
  refuted: 'var(--lyra-negative-rgb)',
  ink: 'var(--lyra-ink-rgb)',
} as const;
const alpha = (rgbVar: string, a: number) => `rgb(${rgbVar} / ${a})`;

function statusColour(status: string): string {
  if (status === 'promoted') return C.champion;
  if (status === 'refuted' || status === 'refuted_as_ranker') return C.refuted;
  return C.challenger; // challenger / challenger_not_promoted / anything held
}

function gradeColour(grade: string): string {
  const l = grade.charAt(0).toUpperCase();
  if (l === 'A') return 'var(--lyra-positive)';
  if (l === 'B') return 'var(--lyra-blue)';
  if (l === 'C') return 'var(--lyra-accent)';
  return 'var(--lyra-negative)';
}

const fmtLift = (v: number) => `${v.toFixed(2)}×`;
const fmtPct = (v: number, dp = 1) => `${(v * 100).toFixed(dp)}%`;
const nf = (n: number) => n.toLocaleString('en-US');

function champion(verdicts: EvidenceVerdict[]): EvidenceVerdict | undefined {
  return (
    verdicts.find((v) => v.model === 'champion' && v.split === 'holdout') ??
    verdicts.find((v) => v.model === 'real_v1' && v.split === 'holdout')
  );
}

/* --------------------------------- small UI atoms --------------------------------- */

function Chip({ colour, rgb, children }: { colour: string; rgb: string; children: React.ReactNode }) {
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-chip px-2.5 py-1 font-mono text-[11px]"
      style={{ color: colour, background: alpha(rgb, 0.1), border: `1px solid ${alpha(rgb, 0.32)}` }}
    >
      <span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: colour }} />
      {children}
    </span>
  );
}

function Eyebrow({ children }: { children: React.ReactNode }) {
  return (
    <p className="mb-1 font-mono text-[10px] font-semibold uppercase tracking-[0.14em] text-positive">{children}</p>
  );
}

/* --------------------------------- charts --------------------------------- */

function VerdictChart({ verdicts }: { verdicts: EvidenceVerdict[] }) {
  const rows = verdicts;
  if (!rows.length) return null;
  const W = 720;
  const rowH = 46;
  const padT = 22;
  const padB = 30;
  const padL = 150;
  const padR = 24;
  const H = padT + rows.length * rowH + padB;
  const hiMax = Math.max(CHANCE_LIFT, ...rows.map((r) => r.ci90[1]));
  const xmax = Math.max(2.5, hiMax + 0.2);
  const plotW = W - padL - padR;
  const X = (v: number) => padL + (v / xmax) * plotW;
  const ticks: number[] = [];
  for (let t = 0; t <= xmax + 0.001; t += 0.5) ticks.push(Number(t.toFixed(1)));

  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full font-mono" role="img" aria-label="Lift over chance by model and split, with 90% confidence intervals">
      {ticks.map((g) => (
        <g key={`t${g}`}>
          <line x1={X(g)} y1={padT - 6} x2={X(g)} y2={H - padB} style={{ stroke: alpha(R.ink, 0.08) }} strokeWidth={1} />
          <text x={X(g)} y={H - padB + 15} textAnchor="middle" fontSize={10} style={{ fill: C.ink3 }}>{g.toFixed(1)}{'×'}</text>
        </g>
      ))}
      <line x1={X(CHANCE_LIFT)} y1={padT - 6} x2={X(CHANCE_LIFT)} y2={H - padB} style={{ stroke: C.nul }} strokeWidth={2} />
      <text x={X(CHANCE_LIFT)} y={padT - 10} textAnchor="middle" fontSize={10} style={{ fill: C.nul }} letterSpacing="0.08em">CHANCE</text>
      {rows.map((v, i) => {
        const cy = padT + i * rowH + rowH / 2;
        const col = statusColour(v.status);
        return (
          <g key={`${v.model}-${v.split}`}>
            <title>{`${v.label} (${v.split}): lift ${fmtLift(v.lift)}, CI [${v.ci90[0].toFixed(2)}, ${v.ci90[1].toFixed(2)}]${v.n != null ? `, n ${nf(v.n)}` : ''}`}</title>
            <text x={padL - 14} y={cy - 3} textAnchor="end" fontSize={12} fontWeight={600} style={{ fill: C.ink }}>{v.label.split(' (')[0].split(' – ')[0].slice(0, 22)}</text>
            <text x={padL - 14} y={cy + 12} textAnchor="end" fontSize={10} style={{ fill: C.ink3 }}>{v.split === 'holdout' ? 'holdout' : 'dev walk-fwd'}</text>
            <line x1={X(v.ci90[0])} y1={cy} x2={X(v.ci90[1])} y2={cy} style={{ stroke: col }} strokeWidth={6} strokeLinecap="round" opacity={0.28} />
            <line x1={X(v.ci90[0])} y1={cy - 5} x2={X(v.ci90[0])} y2={cy + 5} style={{ stroke: col }} strokeWidth={1.5} opacity={0.6} />
            <line x1={X(v.ci90[1])} y1={cy - 5} x2={X(v.ci90[1])} y2={cy + 5} style={{ stroke: col }} strokeWidth={1.5} opacity={0.6} />
            <circle cx={X(v.lift)} cy={cy} r={6} style={{ fill: col, stroke: 'var(--lyra-panel)' }} strokeWidth={2} />
            <text x={X(v.ci90[1]) + 10} y={cy + 4} fontSize={12} fontWeight={600} style={{ fill: col }}>{fmtLift(v.lift)}</text>
          </g>
        );
      })}
    </svg>
  );
}

type Bar = { label: string; v: number; c: string };

function PrecisionBars({ verdicts }: { verdicts: EvidenceVerdict[] }) {
  const ch = champion(verdicts);
  const held = verdicts.find((v) => v.model === 'challenger' && v.split === 'holdout');
  const ref = verdicts.find((v) => v.model === 'reference_scorecard' && v.split === 'holdout');
  const raw: (Bar | null)[] = [
    ch && ch.precisionAtK != null ? { label: 'champion', v: ch.precisionAtK, c: C.champion } : null,
    held && held.precisionAtK != null ? { label: 'challenger', v: held.precisionAtK, c: C.challenger } : null,
    ref && ref.precisionAtK != null ? { label: 'reference', v: ref.precisionAtK, c: C.refuted } : null,
  ];
  const bars = raw.filter((b): b is Bar => b !== null);
  const base = ch?.baseRate ?? null;
  if (!bars.length) return null;
  const W = 340;
  const H = 210;
  const padT = 16;
  const padB = 30;
  const ymax = Math.max(0.3, ...bars.map((b) => b.v), base ?? 0) * 1.1;
  const plotH = H - padT - padB;
  const Y = (v: number) => padT + plotH - (v / ymax) * plotH;
  const gap = W / bars.length;
  const bw = gap * 0.42;
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full font-mono" role="img" aria-label="Holdout top-pick doubler share by model against the random base rate">
      {base != null ? (
        <>
          <line x1={0} y1={Y(base)} x2={W} y2={Y(base)} style={{ stroke: C.nul }} strokeWidth={1.5} strokeDasharray="4 3" />
          <text x={W - 4} y={Y(base) - 6} textAnchor="end" fontSize={10.5} style={{ fill: C.nul }}>{`random ${fmtPct(base)}`}</text>
        </>
      ) : null}
      {bars.map((b, i) => {
        const cx = gap * (i + 0.5);
        const yTop = Y(b.v);
        return (
          <g key={b.label}>
            <title>{`${b.label}: ${fmtPct(b.v)} doubled${base != null ? ` vs ${fmtPct(base)} random` : ''}`}</title>
            <rect x={cx - bw / 2} y={yTop} width={bw} height={padT + plotH - yTop} rx={4} style={{ fill: b.c }} />
            <text x={cx} y={yTop - 8} textAnchor="middle" fontSize={13} fontWeight={600} style={{ fill: b.c }}>{fmtPct(b.v)}</text>
            <text x={cx} y={H - 10} textAnchor="middle" fontSize={11} style={{ fill: C.ink3 }}>{b.label}</text>
          </g>
        );
      })}
    </svg>
  );
}

function CalibrationChart({ bins }: { bins: CalibrationBin[] }) {
  if (bins.length < 2) return null;
  const W = 340;
  const H = 210;
  const pad = 32;
  const hi = Math.max(0.28, ...bins.map((b) => Math.max(b.predicted, b.actual))) * 1.05;
  const plot = W - pad - 14;
  const plotH = H - pad - 14;
  const X = (v: number) => pad + (v / hi) * plot;
  const Y = (v: number) => H - pad - (v / hi) * plotH;
  const grid = [0, 0.1, 0.2].filter((g) => g <= hi);
  const line = bins.map((b) => `${X(b.predicted)},${Y(b.actual)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full font-mono" role="img" aria-label="Reliability curve, predicted versus realised winner rate">
      {grid.map((g) => (
        <g key={`g${g}`}>
          <line x1={X(g)} y1={pad - 14} x2={X(g)} y2={H - pad} style={{ stroke: alpha(R.ink, 0.06) }} strokeWidth={1} />
          <line x1={pad} y1={Y(g)} x2={W - 14} y2={Y(g)} style={{ stroke: alpha(R.ink, 0.06) }} strokeWidth={1} />
          <text x={X(g)} y={H - pad + 14} textAnchor="middle" fontSize={10} style={{ fill: C.ink3 }}>{(g * 100).toFixed(0)}%</text>
          <text x={pad - 6} y={Y(g) + 3} textAnchor="end" fontSize={10} style={{ fill: C.ink3 }}>{(g * 100).toFixed(0)}%</text>
        </g>
      ))}
      <line x1={X(0)} y1={Y(0)} x2={X(hi)} y2={Y(hi)} style={{ stroke: C.nul }} strokeWidth={1.5} strokeDasharray="4 4" />
      <polyline points={line} fill="none" style={{ stroke: C.champion }} strokeWidth={2} strokeLinejoin="round" />
      {bins.map((b) => (
        <circle key={b.bin} cx={X(b.predicted)} cy={Y(b.actual)} r={4} style={{ fill: C.champion, stroke: 'var(--lyra-panel)' }} strokeWidth={1.5}>
          <title>{`predicted ${fmtPct(b.predicted)} - realised ${fmtPct(b.actual)}`}</title>
        </circle>
      ))}
      <text x={pad + 2} y={pad - 6} fontSize={10} style={{ fill: C.ink3 }}>realised rate</text>
      <text x={W - 14} y={H - pad + 14} textAnchor="end" fontSize={10} style={{ fill: C.ink3 }}>predicted</text>
    </svg>
  );
}

function CohortTimeline({ cohorts }: { cohorts: { dev: CohortRow[]; holdout: CohortRow[] } }) {
  const all = [
    ...cohorts.dev.map((r) => ({ ...r, split: 'dev' as const })),
    ...cohorts.holdout.map((r) => ({ ...r, split: 'holdout' as const })),
  ];
  if (!all.length) return null;
  const colW = 26;
  const padT = 18;
  const padB = 44;
  const padL = 38;
  const padR = 12;
  const W = padL + all.length * colW + padR;
  const H = 240;
  const ymax = Math.max(0.5, ...all.map((r) => r.precision_at_k));
  const plotH = H - padT - padB;
  const Y = (v: number) => padT + plotH - (Math.min(v, ymax) / ymax) * plotH;
  const grid = [0, 0.2, 0.4].filter((g) => g <= ymax);
  const bx = padL + cohorts.dev.length * colW;
  return (
    <div className="w-full overflow-x-auto">
      <svg viewBox={`0 0 ${W} ${H}`} width={W} className="block h-auto font-mono" role="img" aria-label="Per-quarter precision against the chance null, dev walk-forward then one-shot holdout">
        {grid.map((g) => (
          <g key={`g${g}`}>
            <line x1={padL} y1={Y(g)} x2={W - padR} y2={Y(g)} style={{ stroke: alpha(R.ink, 0.06) }} strokeWidth={1} />
            <text x={padL - 6} y={Y(g) + 3} textAnchor="end" fontSize={10} style={{ fill: C.ink3 }}>{(g * 100).toFixed(0)}%</text>
          </g>
        ))}
        {cohorts.holdout.length ? (
          <>
            <line x1={bx} y1={padT - 8} x2={bx} y2={padT + plotH} style={{ stroke: C.champion }} strokeWidth={1.5} strokeDasharray="3 3" opacity={0.5} />
            <text x={bx + 4} y={padT - 1} fontSize={10} style={{ fill: C.champion }}>holdout {'→'}</text>
          </>
        ) : null}
        {all.map((d, i) => {
          const cx = padL + i * colW + colW / 2;
          const col = d.split === 'holdout' ? C.champion : C.nul;
          const op = d.split === 'holdout' ? 1 : 0.42;
          const yTop = Y(d.precision_at_k);
          return (
            <g key={`${d.cohort}-${d.split}`}>
              <title>{`${d.cohort} (${d.split}): precision ${fmtPct(d.precision_at_k)}, chance ${fmtPct(d.base_rate)}`}</title>
              <rect x={cx - colW * 0.32} y={yTop} width={colW * 0.64} height={padT + plotH - yTop} rx={3} style={{ fill: col }} opacity={op} />
              <line x1={cx - colW * 0.42} y1={Y(d.base_rate)} x2={cx + colW * 0.42} y2={Y(d.base_rate)} style={{ stroke: C.refuted }} strokeWidth={2} />
              {i % 2 === 0 || d.split === 'holdout' ? (
                <text fontSize={9.5} style={{ fill: C.ink3 }} textAnchor="end" transform={`translate(${cx + 3},${padT + plotH + 10}) rotate(-55)`}>{d.cohort}</text>
              ) : null}
            </g>
          );
        })}
      </svg>
    </div>
  );
}

function WeightFlip({ weights }: { weights: NonNullable<Evidence['weights']> }) {
  const { features, current, baselineSynthetic: syn } = weights;
  const lim = Math.max(0.7, ...current.map((w) => Math.abs(w)), ...syn.map((w) => Math.abs(w)));
  const rowH = 28;
  const padT = 12;
  const padB = 24;
  const padL = 116;
  const padR = 56;
  const W = 720;
  const H = padT + features.length * rowH + padB;
  const plotW = W - padL - padR;
  const midX = padL + plotW / 2;
  const X = (v: number) => midX + (v / lim) * (plotW / 2);
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full font-mono" role="img" aria-label="Standardised logistic weights, synthetic hypothesis versus learned from real outcomes">
      <line x1={midX} y1={padT - 6} x2={midX} y2={H - padB} style={{ stroke: C.nul }} strokeWidth={1.5} />
      {[-0.5, 0.5].map((g) => (
        <g key={`g${g}`}>
          <line x1={X(g)} y1={padT - 6} x2={X(g)} y2={H - padB} style={{ stroke: alpha(R.ink, 0.06) }} strokeWidth={1} />
          <text x={X(g)} y={H - padB + 15} textAnchor="middle" fontSize={10} style={{ fill: C.ink3 }}>{g.toFixed(1)}</text>
        </g>
      ))}
      {features.map((f, i) => {
        const cy = padT + i * rowH + rowH / 2;
        const cur = current[i];
        const s = syn[i];
        const dead = cur === 0;
        const col = cur >= 0 ? C.champion : C.refuted;
        const sx = X(s);
        return (
          <g key={f}>
            <title>{dead ? `${f}: 0.00 - data pipeline unbuilt (never faked)` : `${f}: learned ${cur >= 0 ? '+' : ''}${cur.toFixed(2)}, synthetic ${s >= 0 ? '+' : ''}${s.toFixed(2)}`}</title>
            <text x={padL - 12} y={cy + 3.5} textAnchor="end" fontSize={11.5} style={{ fill: dead ? C.ink3 : C.ink }}>{f.replace(/_/g, ' ')}</text>
            {dead ? (
              <rect x={midX - 5} y={cy - 5} width={10} height={10} rx={2} fill="none" style={{ stroke: C.ink3 }} strokeWidth={1} strokeDasharray="2 2" />
            ) : (
              <rect x={Math.min(X(0), X(cur))} y={cy - 7} width={Math.abs(X(cur) - X(0))} height={14} rx={3} style={{ fill: col }} />
            )}
            <path d={`M ${sx} ${cy - 6} L ${sx + 5} ${cy} L ${sx} ${cy + 6} L ${sx - 5} ${cy} Z`} fill="none" style={{ stroke: C.ink3 }} strokeWidth={1.5} />
          </g>
        );
      })}
    </svg>
  );
}

function LeakageChart({ steps }: { steps: NonNullable<Evidence['leakage']> }) {
  if (!steps.length) return null;
  const W = 720;
  const H = 230;
  const padT = 22;
  const padB = 50;
  const padL = 28;
  const padR = 18;
  const ymax = Math.max(3, ...steps.map((s) => s.lift));
  const plotH = H - padT - padB;
  const Y = (v: number) => padT + plotH - (v / ymax) * plotH;
  const step = (W - padL - padR) / steps.length;
  const linePts = steps.map((s, i) => `${padL + step * (i + 0.5)},${Y(s.lift)}`).join(' ');
  const grid: number[] = [];
  for (let g = 0; g <= ymax + 0.001; g += 1) grid.push(g);
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full font-mono" role="img" aria-label="Leakage decomposition, each fix lowering the lift toward the confirmed number">
      {grid.map((g) => (
        <g key={`g${g}`}>
          <line x1={padL} y1={Y(g)} x2={W - padR} y2={Y(g)} style={{ stroke: alpha(R.ink, 0.06) }} strokeWidth={1} />
          <text x={padL - 6} y={Y(g) + 3} textAnchor="end" fontSize={10} style={{ fill: C.ink3 }}>{g}{'×'}</text>
        </g>
      ))}
      <polyline points={linePts} fill="none" style={{ stroke: C.ink3 }} strokeWidth={1.5} strokeDasharray="3 3" />
      {steps.map((s, i) => {
        const cx = padL + step * (i + 0.5);
        const first = i === 0;
        const col = s.confirm ? C.champion : first ? C.refuted : C.ink2;
        const bw = step * 0.34;
        const yTop = Y(s.lift);
        const words = s.label.split(' ');
        const l1 = words.slice(0, 2).join(' ');
        const l2 = words.slice(2).join(' ');
        return (
          <g key={s.label}>
            <title>{`${s.label}: ${fmtLift(s.lift)}${s.note ? ` - ${s.note}` : ''}`}</title>
            <rect x={cx - bw / 2} y={yTop} width={bw} height={padT + plotH - yTop} rx={4} style={{ fill: col }} opacity={s.confirm || first ? 1 : 0.55} />
            <text x={cx} y={yTop - 9} textAnchor="middle" fontSize={12.5} fontWeight={600} style={{ fill: col }}>{fmtLift(s.lift)}</text>
            {s.confirm ? <text x={cx} y={yTop - 24} textAnchor="middle" fontSize={14} fontWeight={700} style={{ fill: C.champion }}>{'✓'}</text> : null}
            <text x={cx} y={H - padB + 17} textAnchor="middle" fontSize={10.5} style={{ fill: C.ink }}>{l1}</text>
            {l2 ? <text x={cx} y={H - padB + 30} textAnchor="middle" fontSize={10} style={{ fill: C.ink3 }}>{l2}</text> : null}
          </g>
        );
      })}
    </svg>
  );
}

/* --------------------------------- the surface --------------------------------- */

export function ModelVerdict({ evidence = loadModelEvidence() }: { evidence?: Evidence }) {
  const [showPromotion, setShowPromotion] = useState(false);
  const ch = champion(evidence.verdict);
  const corpus = evidence.generatedFromCorpus;
  const calibSeries = evidence.calibration ? (evidence.calibration.real_v1 ?? Object.values(evidence.calibration)[0]) : null;

  const hasAnything =
    evidence.verdict.length > 0 || evidence.weights !== null || evidence.leakage.length > 0 || evidence.grades !== null || evidence.caveat !== null;

  if (!hasAnything) {
    return (
      <section aria-labelledby="model-verdict" className="mt-6">
        <div className="terminal-panel rounded-panel p-4">
          <h3 id="model-verdict" className="text-[13px] font-semibold text-ink">The verdict</h3>
          <p className="mt-1 text-[12px] text-ink-2">
            No evidence artifact is available yet. It is written by the backtest record step after each eval cycle.
          </p>
        </div>
      </section>
    );
  }

  const winners = corpus?.rows != null && corpus?.baseRate != null ? Math.round(corpus.rows * corpus.baseRate) : null;
  const devN = evidence.verdict.find((v) => v.model === 'reference_scorecard' && v.split === 'dev')?.n ?? null;
  const holdoutN = ch?.n ?? null;

  return (
    <section aria-labelledby="model-verdict" className="mt-6 text-ink">
      <Eyebrow>Post-run verdict {'·'} Emerging Winner Engine</Eyebrow>
      <h3 id="model-verdict" className="max-w-[30ch] text-[22px] font-extrabold leading-[1.08] tracking-[-0.02em] text-ink-title sm:text-[26px]">
        Does this model genuinely predict success?
      </h3>
      <p className="mt-2 max-w-[62ch] text-[13px] leading-relaxed text-ink-2">
        Tested against real matured outcomes, not a demo. Two models anti-predict winners; one, retrained on real
        outcomes and confirmed on untouched data, shows genuine calibrated skill and is the deployed champion.
      </p>

      {ch ? (
        <div className="terminal-panel glass-hero rounded-panel mt-4 p-4">
          <div className="grid gap-0 sm:grid-cols-[minmax(0,1.1fr)_minmax(0,1fr)]">
            <div className="sm:border-r sm:border-line-strong sm:pr-5">
              <Eyebrow>Deployed champion {'·'} holdout lift</Eyebrow>
              <div
                className="font-mono font-semibold tabular-nums"
                style={{ fontSize: 'clamp(44px,11vw,76px)', lineHeight: 0.92, letterSpacing: '-0.03em', background: 'var(--lyra-cta-gradient)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent' }}
              >
                {ch.lift.toFixed(2)}
                <span style={{ fontSize: '0.42em', color: 'var(--lyra-blue)' }}>{'×'}</span>
              </div>
              <p className="mt-2 font-mono text-[12px] tabular-nums text-ink-2">
                90% CI [{ch.ci90[0].toFixed(2)} {'–'} {ch.ci90[1].toFixed(2)}]{holdoutN != null ? ` · n = ${nf(holdoutN)}` : ''}
              </p>
              {ch.precisionAtK != null && ch.baseRate != null ? (
                <p className="mt-1 font-mono text-[12px] text-ink-3">
                  top picks were {fmtPct(ch.precisionAtK)} doublers vs {fmtPct(ch.baseRate)} random
                </p>
              ) : null}
            </div>
            <div className="flex flex-col justify-center gap-3 pt-4 sm:pl-5 sm:pt-0">
              <div className="flex flex-wrap gap-2">
                <Chip colour={C.champion} rgb={R.champion}>champion {'·'} promoted</Chip>
                <Chip colour={C.challenger} rgb={R.challenger}>challenger {'·'} held</Chip>
                <Chip colour={C.refuted} rgb={R.refuted}>reference {'·'} refuted</Chip>
              </div>
              <p className="font-mono text-[11px] leading-relaxed text-ink-2">
                Research only {'–'} a resemblance score for a research queue. Never advice, never a price target.
                Surfacing stays shadow-live / Beta, monitor + founder gated.
              </p>
            </div>
          </div>
        </div>
      ) : null}

      {corpus ? (
        <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-6">
          {[
            corpus.rows != null ? { v: nf(corpus.rows), k: 'rows' } : null,
            corpus.symbols != null ? { v: nf(corpus.symbols), k: 'symbols' } : null,
            winners != null ? { v: nf(winners), k: 'winners' } : null,
            corpus.baseRate != null ? { v: fmtPct(corpus.baseRate), k: 'base rate' } : null,
            devN != null && holdoutN != null ? { v: `${nf(devN)}/${nf(holdoutN)}`, k: 'dev / holdout' } : null,
            corpus.curatedRows != null ? { v: nf(corpus.curatedRows), k: 'curated · quarantined' } : null,
          ]
            .filter((t): t is { v: string; k: string } => t !== null)
            .map((t) => (
              <div key={t.k} className="terminal-panel-soft rounded-cell p-3">
                <div className="font-mono text-[19px] font-semibold tabular-nums text-ink">{t.v}</div>
                <div className="mt-0.5 font-mono text-[10px] uppercase tracking-wide text-ink-3">{t.k}</div>
              </div>
            ))}
        </div>
      ) : null}

      <div className="mt-4">
        <Eyebrow>The verdict {'–'} lift over chance, with uncertainty</Eyebrow>
        <div className="terminal-panel rounded-panel p-4">
          <VerdictChart verdicts={evidence.verdict} />
          <div className="mt-3 flex flex-wrap gap-4 font-mono text-[11px] text-ink-2">
            <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.champion }} />champion</span>
            <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.challenger }} />challenger</span>
            <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.refuted }} />reference</span>
            <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-full" style={{ background: C.nul }} />chance = 1.0{'×'}</span>
          </div>
        </div>
        <p className="mt-2 font-mono text-[11px] leading-relaxed text-ink-2">
          Right of the chance line beats random selection. The champion clears 1.0 on both splits; both reference
          incumbents sit fully below it {'–'} their top picks contain fewer winners than random.
        </p>
      </div>

      {(champion(evidence.verdict)?.precisionAtK != null || calibSeries) ? (
        <div className="mt-4 grid gap-3 lg:grid-cols-2">
          <div>
            <Eyebrow>What the top picks contained</Eyebrow>
            <div className="terminal-panel rounded-panel p-4"><PrecisionBars verdicts={evidence.verdict} /></div>
          </div>
          {calibSeries ? (
            <div>
              <Eyebrow>Do the probabilities mean anything?</Eyebrow>
              <div className="terminal-panel rounded-panel p-4">
                <CalibrationChart bins={calibSeries} />
                {ch?.ece != null ? <p className="mt-2 font-mono text-[11px] text-ink-2">Reliability, holdout. ECE {ch.ece.toFixed(3)} {'–'} closer to the diagonal is better.</p> : null}
              </div>
            </div>
          ) : null}
        </div>
      ) : null}

      {evidence.cohorts ? (
        <div className="mt-4">
          <Eyebrow>Regime honesty {'–'} precision quarter by quarter</Eyebrow>
          <div className="terminal-panel rounded-panel p-4">
            <CohortTimeline cohorts={evidence.cohorts} />
            <div className="mt-3 flex flex-wrap gap-4 font-mono text-[11px] text-ink-2">
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.nul, opacity: 0.55 }} />dev walk-forward</span>
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.champion }} />one-shot holdout</span>
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-[2px] w-3.5" style={{ background: C.refuted }} />chance at that quarter{"'"}s base rate</span>
            </div>
          </div>
          <p className="mt-2 font-mono text-[11px] leading-relaxed text-ink-2">
            It beats its null in most quarters, but bear regimes stay thin {'–'} this is why surfacing is not earned yet.
          </p>
        </div>
      ) : null}

      {evidence.weights ? (
        <div className="mt-4">
          <Eyebrow>What real data taught the model</Eyebrow>
          <div className="terminal-panel rounded-panel p-4">
            <WeightFlip weights={evidence.weights} />
            <div className="mt-3 flex flex-wrap gap-4 font-mono text-[11px] text-ink-2">
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.champion }} />learned {'·'} helps</span>
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2 w-2 rounded-[2px]" style={{ background: C.refuted }} />learned {'·'} hurts</span>
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2.5 w-2.5 rotate-45 border border-ink-3" />synthetic hypothesis</span>
              <span className="inline-flex items-center gap-1.5"><span className="inline-block h-2.5 w-2.5 border border-dashed border-ink-3" />0.00 {'·'} pipeline unbuilt</span>
            </div>
            {evidence.weights.note ? <p className="mt-2 text-[11px] leading-relaxed text-ink-2">{evidence.weights.note}</p> : null}
          </div>
          <p className="mt-2 font-mono text-[11px] leading-relaxed text-ink-2">
            The two heaviest hand-designed bets flip negative on real 12-month doublers. Five domains sit at exactly
            zero {'–'} their pipelines are unbuilt, and the model refuses to pretend otherwise.
          </p>
        </div>
      ) : null}

      {evidence.leakage.length ? (
        <div className="mt-4">
          <Eyebrow>How the number was earned</Eyebrow>
          <div className="terminal-panel rounded-panel p-4">
            <LeakageChart steps={evidence.leakage} />
            <p className="mt-3 border-l-2 border-positive pl-3 font-mono text-[11px] leading-relaxed text-ink-2">
              <strong className="text-ink">Standing rule:</strong> any lift above ~2{'×'} from this feature set
              triggers a mandatory leakage decomposition before the number is reported anywhere.
            </p>
          </div>
        </div>
      ) : null}

      {evidence.grades ? (
        <div className="mt-4">
          <Eyebrow>Report card {evidence.grades.gradedAtCorpus ? `· graded at corpus ${evidence.grades.gradedAtCorpus}` : ''}</Eyebrow>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3">
            {evidence.grades.dimensions.map((d) => (
              <div key={d.dimension} className="terminal-panel rounded-cell p-3.5">
                <div className="flex items-baseline justify-between gap-2">
                  <span className="text-[13px] font-bold text-ink">{d.dimension}</span>
                  <span className="font-mono text-[24px] font-semibold" style={{ color: gradeColour(d.grade) }}>{d.grade}</span>
                </div>
                <p className="mt-2 text-[11.5px] leading-relaxed text-ink-2">{d.why}</p>
              </div>
            ))}
          </div>
        </div>
      ) : null}

      <div className="mt-4">
        <Eyebrow>Where this sits {'–'} target state (NORTH-STAR.md)</Eyebrow>
        <div className="terminal-panel rounded-panel p-4">
          <div className="flex flex-col gap-1.5">
            {[
              ['L0', 'screens / hand-picked lists', false],
              ['L1', 'hand-weighted composite scores - reference scorecard (refuted as a ranker)', false],
              ['L2', 'linear model - real labels - honest CV - real-v1 lives here, with L4-grade eval discipline', true],
              ['L3', 'nonlinear tabular (GBDT), interactions, per-regime validation', false],
              ['L4', 'point-in-time multi-source features, delisted-inclusive corpus', false],
              ['L5', 'sequence / graph models, regime conditioning, uncertainty-aware ensembles', false],
            ].map(([lv, txt, here]) => (
              <div
                key={lv as string}
                className={`grid grid-cols-[36px_1fr] items-center gap-3 rounded-cell px-3 py-2 ${here ? 'border border-positive/30 bg-positive/[0.07]' : 'border border-line'}`}
              >
                <span className={`font-mono text-[12px] font-semibold ${here ? 'text-positive' : 'text-ink-3'}`}>{lv as string}{here ? ' ◀' : ''}</span>
                <span className="text-[12.5px] text-ink-2">{txt as string}</span>
              </div>
            ))}
          </div>
          <div className="mt-3 rounded-cell border border-positive/25 p-3" style={{ background: 'linear-gradient(135deg, rgb(var(--lyra-positive-rgb) / 0.09), rgb(var(--lyra-blue-rgb) / 0.07))' }}>
            <div className="mb-1 font-mono text-[10px] uppercase tracking-[0.12em] text-positive">Definition of {'“'}arrived{'”'}</div>
            <p className="text-[12.5px] leading-relaxed text-ink-2">
              Delisted-inclusive holdout: top-pick lift {'≥'} 3.0{'×'} (CI floor {'≥'} 2.0{'×'}) at a
              real ~3% base {'·'} worst quarter beats its null in {'≥'} 90% of quarters {'·'} ECE {'≤'} 0.03
              at deployment prevalence {'·'} live calibration sustains the surfacing gate two quarters. Today{"'"}s lift is
              an optimistic bound on a survivor-biased corpus.
            </p>
          </div>
        </div>
      </div>

      {(evidence.caveat || evidence.labelDiagnostics || evidence.promotion || evidence.deploymentRestatement) ? (
        <div className="mt-4">
          <Eyebrow>Read the numbers with these caveats</Eyebrow>
          <div className="terminal-panel rounded-panel p-4">
            {evidence.caveat ? <p className="text-[12px] leading-relaxed text-ink-2">{evidence.caveat}</p> : null}
            {evidence.deploymentRestatement ? (
              <p className="mt-2 font-mono text-[11.5px] text-ink-2">
                Restated at a {fmtPct(evidence.deploymentRestatement.base, 0)} deployment base rate, top-pick precision
                is {'≈'} {fmtPct(evidence.deploymentRestatement.precision)} {'–'} a research-queue edge, not a tradeable signal.
              </p>
            ) : null}
            {evidence.labelDiagnostics?.note ? (
              <p className="mt-2 text-[11.5px] leading-relaxed text-ink-3">
                {evidence.labelDiagnostics.note}
                {evidence.labelDiagnostics.option4ExcludedStillListed != null && evidence.labelDiagnostics.option4ExcludedLiquidity != null
                  ? ` (excluded by still-listed: ${nf(evidence.labelDiagnostics.option4ExcludedStillListed)} · by liquidity: ${nf(evidence.labelDiagnostics.option4ExcludedLiquidity)})`
                  : ''}
              </p>
            ) : null}
            {evidence.promotion?.reason ? (
              <div className="mt-3 rounded-cell border border-line-strong">
                <button
                  type="button"
                  onClick={() => setShowPromotion((v) => !v)}
                  aria-expanded={showPromotion}
                  className="flex w-full items-center justify-between px-3 py-2 text-left"
                >
                  <span className="text-[11.5px] font-medium text-ink">
                    Promotion justification
                    {evidence.promotion.forcedOverFloor ? (
                      <span className="ml-2 rounded-chip bg-accent-tint px-2 py-0.5 font-mono text-[9px] text-accent">forced over floor</span>
                    ) : null}
                  </span>
                  <ChevronDown size={13} className={`text-ink-3 transition-transform ${showPromotion ? 'rotate-180' : ''}`} />
                </button>
                {showPromotion ? (
                  <div className="border-t border-line px-3 py-2">
                    <p className="text-[11.5px] leading-relaxed text-ink-2">{evidence.promotion.reason}</p>
                    {evidence.promotion.promotedOver ? <p className="mt-1 font-mono text-[10px] text-ink-3">Promoted over: {evidence.promotion.promotedOver}</p> : null}
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
        </div>
      ) : null}

      {(corpus || evidence.evidenceDocs.length) ? (
        <div className="mt-4 border-t border-line pt-3">
          {corpus ? (
            <p className="font-mono text-[10px] text-ink-3">
              {[
                corpus.sha256 ? `corpus ${corpus.sha256.slice(0, 12)}` : null,
                corpus.rows != null ? `${nf(corpus.rows)} rows` : null,
                corpus.dataEnd ? `data to ${corpus.dataEnd}` : null,
                corpus.holdoutStart ? `holdout from ${corpus.holdoutStart}` : null,
              ].filter(Boolean).join(' · ')}
            </p>
          ) : null}
          {evidence.evidenceDocs.length ? (
            <div className="mt-1.5 flex flex-wrap gap-1.5">
              {evidence.evidenceDocs.map((d) => (
                <code key={d} className="rounded bg-well px-1.5 py-0.5 font-mono text-[9px] text-ink-3">{d}</code>
              ))}
            </div>
          ) : null}
        </div>
      ) : null}
    </section>
  );
}
